#!/usr/bin/env ruby -Ku
# coding: utf-8

$LOAD_PATH << '../lib'
require 'pp'
require 'json'
require 'tempfile'
require 'simplecov'
require 'stringio'

SimpleCov.root '..'
SimpleCov.command_name 'test-all'
SimpleCov.start

require 'fc'

FC = 'bin/fc'
EMU = 'bin/emu6502'
err = false
compiler = Fc::Compiler.new

size_prev = JSON.parse( File.read('size_prev.txt') )
size_cur = Hash.new

if ARGV.empty?
  files = Dir.glob 'test_*.fc'
else
  files = ARGV
end

#
# unittest
#

debug_info_tested = false
files.each do |file|
  puts "testing #{file}"

  begin
    StringIO.open do |out|
      result = compiler.build( file, { run: true, stdout: out, debug_info: !debug_info_tested } )
      debug_info_tested = true
      if result != 0
        err = true
        puts out.string
      end
    end
  rescue Fc::CompileError => e
    err = true
    puts e.backtrace[0] + ': ' + e.message
    puts e.backtrace[1..-1]
  end
  # puts result
  
  size_cur[file] = File.size("a.bin")
end

File.write( 'size_cur.txt', JSON.dump( size_cur ) )


# サイズの比較
size_cur.each_key do |file|
  if size_prev[file] and size_cur[file] >= size_prev[file] * 1.1 # 1.1倍は適当
    puts "warning: code size increased, %s %d->%d"%[file, size_prev[file], size_cur[file]]
  end
end

#
# エラーが起こるソースのテスト
#

puts 'testing error on invalid sources'

common = <<EOT
function interrupt():void options(symbol:"_interrupt"){}
function interrupt_irq():void options(symbol:"_interrupt_irq"){}
function main():void{}
EOT

txt = File.read( File.dirname(__FILE__) + '/errors.fc' )
srcs = txt.split(/^\/\/@/m)[1..-1]
srcs.each do |src|

  expected_err, src = src.split(/\n/,2)

  open( Dir.tmpdir+'/fail_test.fc', 'w' ) do |f|
    f.write src+"\n"+common
    f.close

    begin
      compiler.build f.path
    rescue Fc::CompileError => e
      unless /#{expected_err}/ === e.message
        puts e
        puts e.backtrace.join("\n")
        err = true
      end
      print '.'
    end
  end
end
puts


exit(1) if err
