language: ruby
rvm:
  - 1.9.2
  - 2.1.0
  - ruby-head
before_install:
before_script:
script:
  - bundle exec rake test
notifications:
  emails:
    - haramako@gmail.com
  on_success: change
  on_failure: change
