package driver

// @log の Mesen 2 用スクリプト (<rom>.fclog.lua)。Mesen 2 の Lua API (emu.addMemoryCallback の exec、emu.read、
// emu.getState、emu.convertAddress、emu.log) だけを使う。地点の PC に来たら、同じ CPU アドレスに別のバンクが載ることが
// あるので PRG ROM 上の位置まで照合してから、値を副作用の無い読み出しで読んで整形する。書式の規則は formatLogValue と同じ。

import (
	"fmt"
	"sort"
	"strings"
)

func luaString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range []byte(s) {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteByte(r)
		case r < 0x20 || r >= 0x7f:
			fmt.Fprintf(&b, "\\%03d", r)
		default:
			b.WriteByte(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func luaValue(v LogFileValue) string {
	s := fmt.Sprintf("{ loc = %s, addr = %d, reg = %s, value = %d", luaString(v.Loc), v.Addr, luaString(v.Reg), v.Value)
	if len(v.Bytes) > 0 {
		s += ", bytes = {"
		for _, b := range v.Bytes {
			s += " " + luaValue(b) + ","
		}
		s += " }"
	}
	return s + " }"
}

// mesenLogScript は LogFile を埋め込んだ Lua を返す。
func mesenLogScript(lf *LogFile) string {
	var b strings.Builder
	b.WriteString(`-- fc @log for Mesen 2 (generated by fcc build -g; do not edit)
-- Load this script in Mesen (Debug > Script Window) with the ROM built at the same time.
local points = {
`)
	for _, p := range lf.Points {
		fmt.Fprintf(&b, "  { id = %d, file = %s, line = %d,\n    parts = {", p.ID, luaString(p.File), p.Line)
		for _, part := range p.Parts {
			if part.Arg < 0 {
				fmt.Fprintf(&b, " { text = %s },", luaString(part.Text))
			} else {
				fmt.Fprintf(&b, " { arg = %d, verb = %s, width = %d, zero = %t },", part.Arg+1, luaString(part.Verb), part.Width, part.Zero)
			}
		}
		b.WriteString(" },\n    args = {")
		for _, a := range p.Args {
			fmt.Fprintf(&b, " { kind = %s, size = %d, signed = %t", luaString(a.Kind), a.Size, a.Signed)
			if len(a.Enum) > 0 {
				keys := make([]int, 0, len(a.Enum))
				for k := range a.Enum {
					keys = append(keys, k)
				}
				sort.Ints(keys)
				b.WriteString(", enum = {")
				for _, k := range keys {
					fmt.Fprintf(&b, " [%d] = %s,", k, luaString(a.Enum[k]))
				}
				b.WriteString(" }")
			}
			b.WriteString(" },")
		}
		b.WriteString(" },\n    sites = {\n")
		for _, s := range p.Sites {
			prevs := "nil"
			if s.Prevs != nil {
				prevs = "{"
				for _, p := range s.Prevs {
					prevs += fmt.Sprintf(" %d,", p)
				}
				prevs += " }"
			}
			fmt.Fprintf(&b, "      { seq = %d, pc = %d, prg = %d, prevs = %s, values = {", s.Seq, s.PC, s.Prg, prevs)
			for _, v := range s.Values {
				b.WriteString(" " + luaValue(v) + ",")
			}
			b.WriteString(" } },\n")
		}
		b.WriteString("    } },\n")
	}
	b.WriteString(`}

local cpuMem = emu.memType.nesDebug or emu.memType.nesMemory
local prgRom = emu.memType.nesPrgRom

local function readValue(v, size, state)
  if v.loc == "const" then return v.value end
  if v.loc == "bytes" then
    local n = 0
    for i, b in ipairs(v.bytes) do
      local x = readValue(b, 1, state)
      if x == nil then return nil end
      n = n | ((x & 0xff) << (8 * (i - 1)))
    end
    return n
  end
  if v.loc == "reg" then return state["cpu." .. v.reg] end
  if v.loc == "mem" or v.loc == "stack" then
    local addr = v.addr
    if v.loc == "stack" then addr = (addr + state["cpu.x"]) & 0xff end
    local n = 0
    for i = 0, size - 1 do
      n = n | (emu.read((addr + i) & 0xffff, cpuMem, false) << (8 * i))
    end
    return n
  end
  return nil
end

local function toBase(v, base, upper)
  if v == 0 then return "0" end
  local digits = upper and "0123456789ABCDEF" or "0123456789abcdef"
  local s = ""
  while v > 0 do
    local d = v % base
    s = string.sub(digits, d + 1, d + 1) .. s
    v = v // base
  end
  return s
end

local function formatValue(a, part, v)
  local bits = 8 * a.size
  v = v & ((1 << bits) - 1)
  local sv = v
  if a.signed and v >= (1 << (bits - 1)) then sv = v - (1 << bits) end
  local s
  if part.verb == "x" then s = toBase(v, 16, false)
  elseif part.verb == "X" then s = toBase(v, 16, true)
  elseif part.verb == "b" then s = toBase(v, 2, false)
  elseif part.verb == "c" then s = string.char(v)
  elseif part.verb == "d" then s = tostring(sv)
  elseif a.kind == "bool" then s = (v ~= 0) and "true" or "false"
  elseif a.kind == "enum" then s = (a.enum and a.enum[sv]) or tostring(sv)
  elseif a.kind == "ptr" then s = string.format("$%04X", v)
  else s = tostring(sv) end
  if part.width > #s then
    if part.zero and string.sub(s, 1, 1) == "-" then
      s = "-" .. string.rep("0", part.width - #s) .. string.sub(s, 2)
    else
      s = string.rep(part.zero and "0" or " ", part.width - #s) .. s
    end
  end
  return s
end

local function show(p, site)
  local state = emu.getState()
  local out = {}
  for _, part in ipairs(p.parts) do
    if part.text then
      out[#out + 1] = part.text
    else
      local v = readValue(site.values[part.arg], p.args[part.arg].size, state)
      out[#out + 1] = v and formatValue(p.args[part.arg], part, v) or "?"
    end
  end
  emu.log(table.concat(out))
end

-- 同じ PC の地点をまとめてフックする (PRG ROM 上の位置で、今載っているバンクの地点だけ出す。順番は seq = ソースの順)
local byPc = {}
for _, p in ipairs(points) do
  for _, site in ipairs(p.sites) do
    byPc[site.pc] = byPc[site.pc] or {}
    table.insert(byPc[site.pc], { p = p, site = site })
  end
end
for _, list in pairs(byPc) do
  table.sort(list, function(x, y) return x.site.seq < y.site.seq end)
end
-- 合流点の地点 (prevs がある) は、この地点の経路の直前の命令 (prevs) を実行したときに準備し、地点に来たら出して準備を
-- 解く (ループの先頭に付いた @log を後ろからの辺で来た周では出さない、何も出さない else の地点を then の後で出さない)。
-- 準備はその命令を実行したときのサイクル数で持ち、地点に来たときに 1 命令分 (8 サイクル以内) の差のときだけ有効
-- (直前の命令が分岐で、成立してほかへ行った後に別の経路で来たときに出さないように)
local armed = {}
local function cycles()
  local st = emu.getState()
  return st["cpu.cycleCount"]
end
local prevs = {}
for _, p in ipairs(points) do
  for _, site in ipairs(p.sites) do
    if site.prevs then
      for _, pc in ipairs(site.prevs) do
        prevs[pc] = prevs[pc] or {}
        table.insert(prevs[pc], site)
      end
    end
  end
end
for pc, sites in pairs(prevs) do
  emu.addMemoryCallback(function(address)
    local c = cycles() or true
    for _, site in ipairs(sites) do armed[site] = c end
  end, emu.callbackType.exec, pc, pc)
end
for pc, list in pairs(byPc) do
  emu.addMemoryCallback(function(address)
    local abs = nil
    for _, e in ipairs(list) do
      local ok = true
      if e.site.prevs then
        local a = armed[e.site]
        ok = a == true or (type(a) == "number" and (cycles() or a) - a <= 8)
        armed[e.site] = nil
      end
      if ok and e.site.prg >= 0 then
        abs = abs or emu.convertAddress(address, emu.memType.nesMemory)
        ok = abs ~= nil and abs.memType == prgRom and abs.address == e.site.prg
      end
      if ok then show(e.p, e.site) end
    end
  end, emu.callbackType.exec, pc, pc)
end
emu.log("fc @log: " .. #points .. " log points")
`)
	return b.String()
}
