// Code generated by goyacc -o parser.go -p yy parser.y. DO NOT EDIT.

//line parser.y:12

package syntax

import __yyfmt__ "fmt"

//line parser.y:14

//line parser.y:16
type yySymType struct {
	yys     int
	tok     Token
	stmt    Stmt
	stmts   []Stmt
	expr    Expr
	exprs   []Expr
	alist   argList
	typ     TypeExpr
	spec    *VarSpec
	specs   []*VarSpec
	opts    *Options
	optents []*OptionEntry
	params  []*Param
	param   *Param
	cases   []*CaseClause
	kase    *CaseClause
	deflt   *DefaultClause
	block   *Block
	fbody   funcBody
	ident   *Ident
	idents  []*Ident
	use     *UseDecl
	fields  []*FieldDecl
	field   *FieldDecl
	inits   []*FieldInit
	init    *FieldInit
	slit    *StructLit
	optTok  *Token
}

const NUMBER = 57346
const IDENT = 57347
const STRING = 57348
const kPLACEMENT = 57349
const kALIAS = 57350
const kINCLUDE = 57351
const kFUNCTION = 57352
const kCONST = 57353
const kVAR = 57354
const kOPTIONS = 57355
const kIF = 57356
const kELSE = 57357
const kELSIF = 57358
const kLOOP = 57359
const kWHILE = 57360
const kFOR = 57361
const kRETURN = 57362
const kBREAK = 57363
const kCONTINUE = 57364
const kINCBIN = 57365
const kSWITCH = 57366
const kCASE = 57367
const kDEFAULT = 57368
const kUSE = 57369
const kAS = 57370
const kFROM = 57371
const kPUBLIC = 57372
const kPRIVATE = 57373
const kFN = 57374
const kFARFN = 57375
const kBITCAST = 57376
const kSTRUCT = 57377
const kSIZEOF = 57378
const kSOA = 57379
const kTRUE = 57380
const kFALSE = 57381
const kNULL = 57382
const LEQ = 57383
const GEQ = 57384
const EQEQ = 57385
const ADDEQ = 57386
const SUBEQ = 57387
const NEQ = 57388
const ARROW = 57389
const LSHIFT = 57390
const RSHIFT = 57391
const ANDAND = 57392
const OROR = 57393
const INCR = 57394
const DECR = 57395
const MULEQ = 57396
const DIVEQ = 57397
const MODEQ = 57398
const ANDEQ = 57399
const OREQ = 57400
const XOREQ = 57401
const SHLEQ = 57402
const SHREQ = 57403
const UMINUS = 57404
const NO_ELSE = 57405

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMBER",
	"IDENT",
	"STRING",
	"kPLACEMENT",
	"kALIAS",
	"kINCLUDE",
	"kFUNCTION",
	"kCONST",
	"kVAR",
	"kOPTIONS",
	"kIF",
	"kELSE",
	"kELSIF",
	"kLOOP",
	"kWHILE",
	"kFOR",
	"kRETURN",
	"kBREAK",
	"kCONTINUE",
	"kINCBIN",
	"kSWITCH",
	"kCASE",
	"kDEFAULT",
	"kUSE",
	"kAS",
	"kFROM",
	"kPUBLIC",
	"kPRIVATE",
	"kFN",
	"kFARFN",
	"kBITCAST",
	"kSTRUCT",
	"kSIZEOF",
	"kSOA",
	"kTRUE",
	"kFALSE",
	"kNULL",
	"LEQ",
	"GEQ",
	"EQEQ",
	"ADDEQ",
	"SUBEQ",
	"NEQ",
	"ARROW",
	"LSHIFT",
	"RSHIFT",
	"ANDAND",
	"OROR",
	"INCR",
	"DECR",
	"MULEQ",
	"DIVEQ",
	"MODEQ",
	"ANDEQ",
	"OREQ",
	"XOREQ",
	"SHLEQ",
	"SHREQ",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"';'",
	"':'",
	"'<'",
	"'>'",
	"'['",
	"']'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'&'",
	"'|'",
	"'^'",
	"'='",
	"','",
	"'.'",
	"'!'",
	"'~'",
	"UMINUS",
	"NO_ELSE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:353

//line yacctab:1
var yyExca = [...]int16{
	-1, 0,
	1, 3,
	-2, 63,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 3,
	1, 2,
	25, 2,
	26, 2,
	65, 2,
	-2, 63,
	-1, 47,
	65, 3,
	-2, 63,
	-1, 149,
	66, 68,
	-2, 70,
	-1, 399,
	65, 3,
	-2, 63,
	-1, 400,
	25, 3,
	26, 3,
	65, 3,
	-2, 63,
}

const yyPrivate = 57344

const yyLast = 1909

var yyAct = [...]int16{
	17, 351, 23, 235, 2, 5, 207, 214, 357, 240,
	285, 58, 12, 286, 167, 284, 69, 67, 162, 18,
	160, 271, 342, 143, 142, 113, 114, 115, 116, 136,
	107, 126, 127, 128, 129, 130, 131, 135, 108, 400,
	361, 333, 117, 60, 229, 68, 360, 244, 336, 335,
	76, 331, 141, 401, 139, 134, 229, 155, 332, 254,
	265, 135, 163, 168, 332, 157, 332, 332, 299, 332,
	277, 135, 262, 175, 375, 169, 146, 176, 177, 179,
	180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
	190, 191, 192, 193, 194, 195, 196, 197, 198, 199,
	200, 201, 202, 203, 204, 205, 206, 178, 215, 216,
	106, 255, 248, 243, 232, 344, 245, 341, 125, 106,
	293, 149, 225, 158, 231, 220, 106, 244, 244, 246,
	104, 105, 399, 218, 224, 223, 386, 385, 60, 230,
	398, 263, 236, 221, 107, 60, 373, 222, 59, 348,
	372, 233, 108, 107, 78, 79, 80, 81, 82, 366,
	107, 108, 260, 365, 76, 80, 81, 82, 108, 41,
	9, 45, 22, 76, 19, 47, 313, 237, 46, 7,
	76, 300, 8, 10, 11, 15, 13, 14, 39, 16,
	150, 267, 257, 247, 174, 20, 21, 112, 111, 29,
	413, 38, 405, 42, 43, 44, 387, 374, 355, 346,
	268, 272, 40, 280, 266, 270, 250, 25, 26, 173,
	172, 281, 282, 171, 170, 109, 63, 27, 261, 47,
	209, 24, 135, 28, 242, 36, 47, 33, 32, 34,
	289, 320, 35, 290, 291, 256, 60, 303, 30, 31,
	294, 57, 377, 47, 397, 345, 329, 211, 212, 302,
	298, 304, 297, 135, 135, 314, 318, 69, 301, 296,
	317, 312, 106, 276, 306, 156, 337, 275, 328, 327,
	323, 274, 316, 315, 319, 102, 103, 253, 249, 228,
	324, 325, 104, 105, 227, 210, 217, 140, 138, 208,
	137, 339, 334, 72, 62, 61, 107, 56, 252, 338,
	358, 383, 100, 101, 108, 358, 78, 79, 80, 81,
	82, 64, 279, 343, 352, 353, 76, 350, 46, 359,
	234, 153, 343, 241, 321, 349, 66, 154, 367, 310,
	309, 110, 369, 363, 308, 371, 307, 364, 144, 343,
	292, 258, 362, 152, 147, 378, 168, 145, 376, 215,
	343, 65, 118, 368, 119, 382, 384, 340, 169, 4,
	380, 370, 305, 48, 239, 238, 394, 213, 395, 388,
	389, 326, 356, 381, 151, 251, 392, 393, 133, 37,
	159, 347, 402, 403, 311, 148, 6, 379, 165, 408,
	409, 3, 328, 1, 410, 411, 106, 236, 412, 0,
	0, 0, 343, 414, 343, 404, 415, 406, 0, 102,
	103, 98, 88, 89, 99, 0, 104, 105, 86, 87,
	74, 75, 90, 91, 92, 93, 94, 95, 96, 97,
	107, 0, 0, 0, 73, 0, 100, 101, 108, 106,
	78, 79, 80, 81, 82, 83, 84, 85, 77, 0,
	76, 0, 102, 103, 98, 88, 89, 99, 0, 104,
	105, 86, 87, 74, 75, 90, 91, 92, 93, 94,
	95, 96, 97, 107, 0, 0, 0, 0, 0, 100,
	101, 108, 106, 78, 79, 80, 81, 82, 83, 84,
	85, 77, 0, 76, 0, 102, 103, 98, 88, 89,
	99, 0, 104, 105, 86, 87, 0, 0, 90, 91,
	92, 93, 94, 95, 96, 97, 107, 407, 0, 0,
	46, 0, 100, 101, 108, 0, 78, 79, 80, 81,
	82, 83, 84, 85, 77, 106, 76, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 102, 103,
	98, 88, 89, 99, 0, 104, 105, 86, 87, 0,
	0, 90, 91, 92, 93, 94, 95, 96, 97, 107,
	0, 0, 0, 0, 0, 100, 101, 108, 106, 78,
	79, 80, 81, 82, 83, 84, 85, 77, 0, 76,
	0, 102, 103, 98, 88, 89, 99, 0, 104, 105,
	86, 87, 0, 0, 90, 91, 92, 93, 94, 95,
	96, 97, 107, 396, 0, 0, 0, 0, 100, 101,
	108, 106, 78, 79, 80, 81, 82, 83, 84, 85,
	77, 0, 76, 0, 102, 103, 98, 88, 89, 99,
	0, 104, 105, 86, 87, 0, 0, 90, 91, 92,
	93, 94, 95, 96, 97, 107, 0, 0, 0, 391,
	0, 100, 101, 108, 106, 78, 79, 80, 81, 82,
	83, 84, 85, 77, 0, 76, 0, 102, 103, 98,
	88, 89, 99, 0, 104, 105, 86, 87, 0, 0,
	90, 91, 92, 93, 94, 95, 96, 97, 107, 390,
	0, 0, 0, 0, 100, 101, 108, 106, 78, 79,
	80, 81, 82, 83, 84, 85, 77, 0, 76, 0,
	102, 103, 98, 88, 89, 99, 0, 104, 105, 86,
	87, 0, 0, 90, 91, 92, 93, 94, 95, 96,
	97, 107, 0, 0, 0, 0, 0, 100, 101, 108,
	106, 78, 79, 80, 81, 82, 83, 84, 85, 77,
	354, 76, 0, 102, 103, 98, 88, 89, 99, 0,
	104, 105, 86, 87, 0, 0, 90, 91, 92, 93,
	94, 95, 96, 97, 107, 0, 0, 0, 0, 0,
	100, 101, 108, 330, 78, 79, 80, 81, 82, 83,
	84, 85, 77, 106, 76, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 102, 103, 98, 88,
	89, 99, 0, 104, 105, 86, 87, 0, 0, 90,
	91, 92, 93, 94, 95, 96, 97, 107, 0, 0,
	0, 0, 0, 100, 101, 108, 322, 78, 79, 80,
	81, 82, 83, 84, 85, 77, 106, 76, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 102,
	103, 98, 88, 89, 99, 0, 104, 105, 86, 87,
	0, 0, 90, 91, 92, 93, 94, 95, 96, 97,
	107, 0, 0, 0, 0, 0, 100, 101, 108, 288,
	78, 79, 80, 81, 82, 83, 84, 85, 77, 106,
	76, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 102, 103, 98, 88, 89, 99, 0, 104,
	105, 86, 87, 0, 0, 90, 91, 92, 93, 94,
	95, 96, 97, 107, 0, 0, 0, 0, 0, 100,
	101, 108, 278, 78, 79, 80, 81, 82, 83, 84,
	85, 77, 106, 76, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 102, 103, 98, 88, 89,
	99, 0, 104, 105, 86, 87, 0, 0, 90, 91,
	92, 93, 94, 95, 96, 97, 107, 269, 0, 0,
	0, 0, 100, 101, 108, 106, 78, 79, 80, 81,
	82, 83, 84, 85, 77, 0, 76, 0, 102, 103,
	98, 88, 89, 99, 0, 104, 105, 86, 87, 0,
	0, 90, 91, 92, 93, 94, 95, 96, 97, 107,
	264, 0, 0, 0, 0, 100, 101, 108, 106, 78,
	79, 80, 81, 82, 83, 84, 85, 77, 0, 76,
	0, 102, 103, 98, 88, 89, 99, 0, 104, 105,
	86, 87, 0, 0, 90, 91, 92, 93, 94, 95,
	96, 97, 107, 259, 0, 0, 0, 0, 100, 101,
	108, 106, 78, 79, 80, 81, 82, 83, 84, 85,
	77, 0, 76, 0, 102, 103, 98, 88, 89, 99,
	0, 104, 105, 86, 87, 0, 0, 90, 91, 92,
	93, 94, 95, 96, 97, 107, 219, 0, 0, 0,
	0, 100, 101, 108, 106, 78, 79, 80, 81, 82,
	83, 84, 85, 77, 124, 76, 0, 102, 103, 98,
	88, 89, 99, 0, 104, 105, 86, 87, 106, 0,
	90, 91, 92, 93, 94, 95, 96, 97, 107, 0,
	0, 122, 123, 0, 100, 101, 108, 0, 78, 79,
	80, 81, 82, 83, 84, 85, 77, 287, 76, 41,
	164, 45, 107, 0, 0, 0, 0, 166, 0, 0,
	108, 0, 78, 79, 80, 81, 82, 0, 39, 121,
	0, 0, 76, 120, 122, 123, 0, 0, 0, 29,
	0, 38, 0, 42, 43, 44, 0, 0, 0, 0,
	0, 0, 40, 0, 0, 0, 0, 25, 26, 0,
	0, 41, 71, 45, 0, 0, 0, 27, 0, 0,
	0, 0, 121, 28, 0, 36, 120, 33, 32, 34,
	39, 0, 35, 0, 0, 0, 0, 0, 30, 31,
	0, 29, 0, 38, 0, 42, 43, 44, 0, 50,
	0, 52, 51, 49, 40, 0, 0, 0, 0, 25,
	26, 0, 0, 41, 71, 45, 0, 0, 53, 27,
	0, 0, 0, 0, 0, 28, 54, 36, 55, 33,
	32, 34, 39, 0, 35, 0, 0, 0, 0, 0,
	30, 31, 0, 29, 0, 38, 0, 42, 43, 44,
	0, 0, 0, 0, 0, 0, 40, 0, 0, 0,
	0, 0, 0, 0, 0, 41, 71, 45, 0, 0,
	0, 27, 0, 70, 0, 0, 0, 28, 0, 36,
	295, 33, 32, 34, 39, 0, 35, 0, 0, 0,
	0, 0, 30, 31, 0, 29, 0, 38, 0, 42,
	43, 44, 0, 0, 0, 0, 0, 0, 40, 0,
	0, 0, 0, 0, 0, 0, 0, 41, 71, 45,
	0, 0, 0, 27, 0, 70, 0, 0, 0, 28,
	0, 36, 132, 33, 32, 34, 39, 0, 35, 0,
	0, 0, 0, 0, 30, 31, 0, 29, 0, 38,
	0, 42, 43, 44, 0, 0, 0, 0, 0, 0,
	40, 0, 0, 0, 0, 0, 0, 0, 0, 41,
	161, 45, 0, 0, 0, 27, 0, 70, 0, 0,
	0, 28, 0, 36, 0, 33, 32, 34, 39, 0,
	35, 0, 0, 0, 0, 0, 30, 31, 0, 29,
	0, 38, 0, 42, 43, 44, 0, 0, 0, 0,
	0, 0, 40, 0, 0, 0, 0, 0, 0, 0,
	0, 41, 71, 45, 0, 0, 0, 27, 0, 70,
	0, 0, 0, 28, 0, 36, 0, 33, 32, 34,
	39, 0, 35, 0, 0, 0, 0, 0, 30, 31,
	0, 29, 0, 38, 0, 42, 43, 44, 0, 0,
	0, 0, 0, 0, 40, 0, 0, 0, 0, 0,
	0, 0, 0, 41, 71, 45, 0, 0, 0, 27,
	0, 0, 0, 0, 0, 28, 0, 36, 283, 33,
	32, 34, 39, 0, 35, 0, 0, 0, 0, 0,
	30, 31, 0, 29, 0, 38, 0, 42, 43, 44,
	0, 0, 0, 0, 0, 0, 40, 0, 0, 0,
	0, 0, 0, 0, 0, 41, 71, 45, 0, 0,
	0, 27, 0, 0, 0, 0, 0, 28, 0, 36,
	273, 33, 32, 34, 39, 0, 35, 0, 0, 0,
	0, 0, 30, 31, 0, 29, 0, 38, 0, 42,
	43, 44, 0, 0, 0, 0, 0, 0, 40, 0,
	0, 0, 0, 0, 0, 0, 0, 41, 71, 45,
	0, 0, 0, 27, 0, 0, 0, 0, 0, 28,
	0, 36, 226, 33, 32, 34, 39, 0, 35, 0,
	0, 0, 0, 0, 30, 31, 0, 29, 0, 38,
	0, 42, 43, 44, 0, 0, 0, 0, 106, 0,
	40, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 102, 103, 98, 0, 27, 99, 0, 104, 105,
	86, 28, 0, 36, 0, 33, 32, 34, 0, 0,
	35, 0, 107, 0, 0, 0, 30, 31, 100, 101,
	108, 106, 78, 79, 80, 81, 82, 83, 84, 85,
	0, 0, 76, 0, 102, 103, 98, 0, 0, 99,
	0, 104, 105, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 107, 0, 0, 0, 0,
	0, 100, 101, 108, 106, 78, 79, 80, 81, 82,
	83, 84, 85, 0, 0, 76, 0, 102, 103, 98,
	0, 0, 99, 0, 104, 105, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 107, 0,
	0, 0, 0, 0, 100, 101, 108, 106, 78, 79,
	80, 81, 82, 83, 0, 85, 0, 0, 76, 0,
	102, 103, 98, 0, 106, 99, 0, 104, 105, 0,
	0, 0, 0, 0, 0, 0, 0, 102, 103, 98,
	0, 107, 99, 0, 104, 105, 0, 100, 101, 108,
	0, 78, 79, 80, 81, 82, 83, 0, 107, 0,
	0, 76, 0, 0, 100, 101, 108, 0, 78, 79,
	80, 81, 82, 0, 0, 0, 0, 0, 76,
}

var yyPact = [...]int16{
	165, -32768, -32768, 165, -32768, -32768, 1281, 245, 189, 81,
	243, 242, 160, 356, 356, 1403, 241, 378, 159, 356,
	131, 130, 172, -32768, -32768, 1663, 1663, 1663, 1149, 50,
	1663, 1663, 1663, 1663, 1663, 1663, 1351, -32768, 238, 236,
	1149, -32768, -32768, -32768, -32768, -32768, 235, 165, -32768, 343,
	352, 343, 349, 116, 348, 326, 1663, 212, -32768, 165,
	1455, 1663, 1195, -32768, 158, -32768, 157, 154, 153, 1116,
	1455, 182, 1663, -32768, -32768, -32768, 1663, 1403, 1663, 1663,
	1663, 1663, 1663, 1663, 1663, 1663, 1663, 1663, 1663, 1663,
	1663, 1663, 1663, 1663, 1663, 1663, 1663, 1663, 1663, 1663,
	1663, 1663, 1663, 1663, 1663, 1663, 225, 1663, 1663, -32768,
	234, -32768, -32768, 315, 1116, 1116, 1073, 56, -32768, 73,
	1149, 1611, 232, 227, -38, 1149, -32, -32, -32, -32,
	-32, -32, -32768, 43, -32768, 1116, -32768, 1149, 324, 111,
	328, 169, 47, -32768, 49, 126, 46, 226, 150, 280,
	258, 30, 181, 125, 346, 1030, 165, -32768, 163, -9,
	-32768, 74, -32768, 987, -21, 148, 343, -32768, 421, -32768,
	-32768, -32768, -32768, -32768, 145, 944, -32768, 1116, -32768, 91,
	91, 98, 98, 98, 1826, 1766, 1809, 1723, 1680, 1116,
	1116, 1116, 1116, 1116, 1116, 1116, 1116, 1116, 1116, 244,
	244, 82, 82, 82, 82, 1140, 1140, -32768, 225, -61,
	1559, 219, 215, 210, -11, 1116, 891, 316, 147, -32768,
	1663, 1507, -32768, 1192, -32768, 838, 1149, 1192, 1192, 345,
	51, 1299, -32768, 206, 199, -32768, -32768, -32768, 197, -13,
	-32768, 114, -32768, -32768, 343, 1149, 1663, 1149, -32768, 343,
	-32768, -32768, 341, 339, 335, 334, -32768, 1149, 109, 165,
	-32768, -32768, 1455, 1403, 165, 1663, 1663, -34, -32768, 177,
	-32768, 329, 785, 225, 1192, 1192, 172, 1663, -32768, 193,
	-32768, 82, 732, -32768, -12, -32768, -32768, -26, 1149, -32768,
	-14, -15, -32768, 214, -32768, -32768, -32768, -32768, -32768, 328,
	1663, -32768, 37, 517, 35, 192, -34, -32768, -32768, -32768,
	-32768, 144, 315, 1149, 309, -32768, -32768, -32768, 689, 142,
	290, -32768, 225, -32768, -17, -23, -32768, -32768, 1116, 315,
	-32768, -32768, 1192, 1149, -32768, 96, 92, 1663, -32768, 1116,
	315, 1403, -32768, -32768, 1663, 83, -32768, -32768, 79, 141,
	-6, -32768, 165, 190, 1663, 1247, 285, -32768, 1663, -32768,
	70, 69, 140, -32768, -32768, 1149, 1149, 646, -32768, 1116,
	-32768, 603, 1149, 1149, -32768, 1663, -32768, 1663, 560, 191,
	-32768, 75, -32768, 65, -28, 225, 225, -32768, -32768, -32768,
	-32768, -32768, 315, 136, 517, 464, 172, 172, -32768, 165,
	165, 1663, -32768, -32768, 111, -32768, 134, 165, -32768, -32768,
	-32768, -32768, -32768, -32768, 309, -32768,
}

var yyPgo = [...]int16{
	0, 403, 4, 401, 369, 5, 1, 398, 397, 14,
	12, 396, 395, 394, 391, 390, 123, 20, 389, 29,
	18, 388, 385, 321, 384, 383, 382, 8, 2, 381,
	3, 17, 0, 7, 377, 22, 19, 375, 374, 9,
	372, 24, 23, 367, 13, 364, 6, 362, 15, 10,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 4, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 13, 13, 14, 18,
	19, 16, 16, 16, 15, 15, 17, 17, 20, 20,
	21, 21, 7, 7, 7, 8, 8, 9, 9, 10,
	10, 10, 10, 11, 11, 12, 12, 12, 22, 22,
	24, 24, 23, 23, 25, 25, 26, 26, 27, 30,
	30, 28, 29, 29, 6, 6, 6, 31, 31, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 33, 33, 34, 34, 34,
	35, 35, 36, 37, 38, 38, 39, 40, 40, 41,
	41, 42, 42, 43, 43, 43, 44, 44, 47, 47,
	47, 47, 47, 46, 46, 46, 46, 46, 46, 46,
	45, 45, 45, 45, 45, 45, 48, 48, 48, 49,
	49,
}

var yyR2 = [...]int8{
	0, 1, 1, 0, 2, 1, 1, 4, 8, 4,
	6, 4, 2, 3, 5, 9, 9, 2, 3, 3,
	3, 3, 8, 2, 10, 2, 4, 6, 7, 10,
	7, 2, 2, 4, 1, 1, 0, 2, 4, 4,
	3, 0, 1, 2, 1, 3, 3, 1, 1, 1,
	1, 3, 0, 2, 1, 0, 1, 1, 1, 2,
	2, 2, 2, 0, 1, 2, 3, 3, 0, 2,
	1, 3, 0, 1, 0, 3, 2, 1, 4, 1,
	1, 3, 0, 1, 0, 2, 6, 0, 1, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 4, 3, 7, 2, 2, 2, 2, 2, 2,
	5, 4, 2, 3, 4, 1, 4, 4, 3, 1,
	1, 1, 1, 1, 1, 3, 1, 0, 1, 2,
	0, 1, 4, 1, 3, 1, 3, 0, 1, 3,
	1, 5, 4, 0, 2, 2, 1, 1, 2, 4,
	3, 6, 6, 2, 3, 4, 3, 6, 6, 1,
	3, 4, 3, 2, 4, 1, 3, 1, 0, 1,
	3,
}

var yyChk = [...]int16{
	-32768, -1, -2, -3, -4, -5, -11, 14, 17, 5,
	18, 19, -10, 21, 22, 20, 24, -32, -36, 9,
	30, 31, 7, -28, 66, 52, 53, 62, 68, 34,
	83, 84, 73, 72, 74, 77, 70, -18, 36, 23,
	47, 4, 38, 39, 40, 6, 13, 64, -4, 12,
	8, 11, 10, 27, 35, 37, 62, 62, -28, 67,
	64, 62, 62, 66, -23, 5, -23, -31, -19, -32,
	64, 5, 62, 66, 52, 53, 82, 80, 72, 73,
	74, 75, 76, 77, 78, 79, 50, 51, 44, 45,
	54, 55, 56, 57, 58, 59, 60, 61, 43, 46,
	68, 69, 41, 42, 48, 49, 28, 62, 70, 66,
	-23, 67, 67, -28, -32, -32, -32, -44, -47, -45,
	74, 70, 32, 33, 5, 68, -32, -32, -32, -32,
	-32, -32, 71, -21, -20, -32, -19, 62, 62, -44,
	62, -2, -41, -42, 5, 5, -41, 5, -12, 5,
	74, -24, 5, 5, 11, -32, 63, -5, -16, -15,
	-17, 5, -20, -32, 5, -7, 12, -9, -32, -10,
	66, 66, 66, 66, -16, -32, -32, -32, -19, -32,
	-32, -32, -32, -32, -32, -32, -32, -32, -32, -32,
	-32, -32, -32, -32, -32, -32, -32, -32, -32, -32,
	-32, -32, -32, -32, -32, -32, -32, -46, 74, 5,
	70, 32, 33, -34, -33, -32, -32, 62, -36, 63,
	69, 70, 74, 62, -44, -32, 71, 62, 62, 82,
	-44, 81, 71, -44, 6, -30, -28, 66, -37, -38,
	-39, 5, 65, 66, 81, 67, 80, 67, 66, 62,
	66, -22, 28, 29, 29, 81, 64, 67, 5, 63,
	-5, 65, 81, 67, 63, 81, 66, -41, 65, 63,
	-46, 82, -32, 71, 62, 62, 63, 81, 71, 6,
	66, -32, -32, 71, -48, -49, -44, 5, 71, -44,
	-48, -48, 5, 69, -20, 71, 63, 63, 63, 81,
	67, -42, -44, -32, -44, -40, -41, 5, 5, 5,
	5, -13, -44, 67, -5, -17, -20, -5, -32, -31,
	64, 5, 71, -46, -48, -48, -29, -28, -32, 63,
	71, 63, 81, 67, -44, 63, 63, 62, -39, -32,
	-43, 80, -35, -36, 80, 63, 65, -14, 5, -35,
	-44, -6, 15, 16, 81, 66, -26, -27, 25, -46,
	63, 63, -35, -49, -44, 67, 67, -32, -35, -32,
	-19, -32, 67, 67, 66, 80, -5, 62, -32, -8,
	-9, -25, -27, 26, -33, 67, 67, 66, -44, -44,
	63, 66, -44, -44, -32, -32, 63, 63, 65, 67,
	67, 81, -46, -46, -35, 66, -35, 63, -28, -28,
	-2, -2, -30, 66, -5, -6,
}

var yyDef = [...]int16{
	-2, -2, 1, -2, 5, 6, 0, 0, 0, 143,
	0, 0, 0, 72, 72, 87, 0, 0, 0, 72,
	64, 0, 0, 34, 35, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 135, 0, 0,
	0, 139, 140, 141, 142, 144, 0, -2, 4, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 12, 63,
	41, 0, 52, 17, 0, 73, 0, 0, 0, 88,
	41, 143, 0, 23, 59, 60, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 147, 0, 25,
	0, 31, 32, 0, 61, 62, 0, 0, 166, 167,
	0, 0, 0, 0, 185, 0, 124, 125, 126, 127,
	128, 129, 132, 0, 50, 48, 49, 0, 0, 0,
	0, 0, 0, 160, 0, 0, 0, 0, 0, -2,
	0, 0, 0, 0, 0, 0, 63, 13, 0, 42,
	44, 143, 47, 0, 143, 0, 0, 54, 57, 58,
	18, 19, 20, 21, 0, 0, 90, 91, 92, 93,
	94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
	104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
	114, 115, 116, 117, 118, 119, 120, 122, 0, 179,
	0, 0, 0, 0, 148, 146, 0, 0, 0, 89,
	0, 0, 183, 188, 168, 0, 0, 188, 188, 0,
	0, 0, 133, 0, 0, 138, 79, 80, 0, 153,
	155, 0, 81, 7, 0, 0, 0, 0, 9, 157,
	26, 65, 0, 0, 0, 0, 36, 0, 0, 63,
	11, 39, 43, 0, 63, 0, 87, 53, 40, 0,
	173, 0, 0, 0, 188, 188, 82, 149, 131, 0,
	33, 121, 0, 182, 0, 187, 189, 185, 0, 170,
	0, 0, 180, 0, 51, 134, 136, 137, 152, 0,
	0, 159, 163, 150, 0, 0, 158, 69, 66, 67,
	71, 0, 150, 0, 84, 45, 46, 14, 0, 0,
	0, 174, 0, 176, 0, 0, 130, 83, 145, 150,
	181, 184, 0, 0, 169, 0, 0, 0, 154, 156,
	150, 0, 162, 151, 0, 0, 27, 37, 0, 0,
	0, 10, 63, 0, 0, 55, 74, 77, 0, 175,
	0, 0, 0, 186, 190, 0, 0, 0, 161, 164,
	165, 0, 0, 0, 28, 0, 85, 0, 0, 0,
	56, 0, 76, 0, 0, 0, 0, 30, 171, 172,
	123, 8, 150, 0, 150, 0, 0, 0, 22, -2,
	-2, 0, 177, 178, 0, 38, 0, 63, 15, 16,
	75, 78, 24, 29, 84, 86,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 83, 3, 3, 3, 76, 77, 3,
	62, 63, 74, 72, 81, 73, 82, 75, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 67, 66,
	68, 80, 69, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 70, 3, 71, 79, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 64, 78, 65, 84,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	85, 86,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:103
		{
			yylex.(*yyLexAdapter).result = yyDollar[1].stmts
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:109
		{
			yyVAL.stmts = []Stmt{}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:111
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:112
		{
			yyVAL.stmts = []Stmt{yyDollar[1].stmt}
		}
	case 7:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:116
		{
			yyVAL.stmt = &VarDecl{PublicPos: optPos(yyDollar[1].optTok), Keyword: yyDollar[2].tok.Pos, Specs: yyDollar[3].specs, Semi: yyDollar[4].tok.Pos}
		}
	case 8:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.y:117
		{
			yyVAL.stmt = &VarDecl{PublicPos: optPos(yyDollar[1].optTok), Keyword: yyDollar[2].tok.Pos, Alias: true, Specs: []*VarSpec{{Name: ident(yyDollar[3].tok), Type: yyDollar[5].typ, Init: yyDollar[7].expr}}, Semi: yyDollar[8].tok.Pos}
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:118
		{
			yyVAL.stmt = &VarDecl{PublicPos: optPos(yyDollar[1].optTok), Keyword: yyDollar[2].tok.Pos, Const: true, Specs: yyDollar[3].specs, Semi: yyDollar[4].tok.Pos}
		}
	case 10:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:119
		{
			yyVAL.stmt = &IfStmt{If: yyDollar[1].tok.Pos, Lparen: yyDollar[2].tok.Pos, Cond: yyDollar[3].expr, Rparen: yyDollar[4].tok.Pos, Then: yyDollar[5].stmt, Else: yyDollar[6].stmt}
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:120
		{
			yyVAL.stmt = &LoopStmt{Loop: yyDollar[1].tok.Pos, Rparen: yyDollar[3].tok.Pos, Body: yyDollar[4].stmt}
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:121
		{
			yyVAL.stmt = &LoopStmt{Loop: yyDollar[1].tok.Pos, Body: yyDollar[2].block}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:122
		{
			yyVAL.stmt = &LabeledStmt{Label: ident(yyDollar[1].tok), Colon: yyDollar[2].tok.Pos, Stmt: yyDollar[3].stmt}
		}
	case 14:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:123
		{
			yyVAL.stmt = &WhileStmt{While: yyDollar[1].tok.Pos, Cond: yyDollar[3].expr, Rparen: yyDollar[4].tok.Pos, Body: yyDollar[5].stmt}
		}
	case 15:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.y:124
		{
			yyVAL.stmt = &ForStmt{For: yyDollar[1].tok.Pos, Var: ident(yyDollar[3].tok), From: yyDollar[5].expr, To: yyDollar[7].expr, Rparen: yyDollar[8].tok.Pos, Body: yyDollar[9].block}
		}
	case 16:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.y:126
		{
			yyVAL.stmt = &ForStmt{For: yyDollar[1].tok.Pos, Init: yyDollar[3].stmt, Cond: yyDollar[5].expr, Step: yyDollar[7].stmt, Rparen: yyDollar[8].tok.Pos, Body: yyDollar[9].block}
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:127
		{
			s := yyDollar[1].stmt.(*IncDecStmt)
			s.Semi = yyDollar[2].tok.Pos
			yyVAL.stmt = s
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:128
		{
			yyVAL.stmt = &BreakStmt{Keyword: yyDollar[1].tok.Pos, Label: yyDollar[2].ident, Semi: yyDollar[3].tok.Pos}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:129
		{
			yyVAL.stmt = &ContinueStmt{Keyword: yyDollar[1].tok.Pos, Label: yyDollar[2].ident, Semi: yyDollar[3].tok.Pos}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:130
		{
			yyVAL.stmt = &ReturnStmt{Return: yyDollar[1].tok.Pos, Value: yyDollar[2].expr, Semi: yyDollar[3].tok.Pos}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:131
		{
			yyVAL.stmt = &ReturnStmt{Return: yyDollar[1].tok.Pos, Value: yyDollar[2].slit, Semi: yyDollar[3].tok.Pos}
		}
	case 22:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.y:132
		{
			yyVAL.stmt = &SwitchStmt{Switch: yyDollar[1].tok.Pos, Tag: yyDollar[3].expr, Lbrace: yyDollar[5].tok.Pos, Cases: yyDollar[6].cases, Default: yyDollar[7].deflt, Rbrace: yyDollar[8].tok.Pos}
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:133
		{
			yyVAL.stmt = &ExprStmt{X: yyDollar[1].expr, Semi: yyDollar[2].tok.Pos}
		}
	case 24:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser.y:135
		{
			yyVAL.stmt = funcDecl(yyDollar[1].optTok, yyDollar[2].tok, yyDollar[3].tok, yyDollar[5].specs, yyDollar[8].typ, yyDollar[9].opts, yyDollar[10].fbody)
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:136
		{
			yyVAL.stmt = &OptionsStmt{Options: yyDollar[1].opts, Semi: yyDollar[2].tok.Pos}
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:137
		{
			u := yyDollar[3].use
			u.PublicPos = optPos(yyDollar[1].optTok)
			u.Use = yyDollar[2].tok.Pos
			u.Semi = yyDollar[4].tok.Pos
			yyVAL.stmt = u
		}
	case 27:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:138
		{
			yyVAL.stmt = &StructDecl{PublicPos: optPos(yyDollar[1].optTok), Keyword: yyDollar[2].tok.Pos, Name: ident(yyDollar[3].tok), Lbrace: yyDollar[4].tok.Pos, Fields: yyDollar[5].fields, Rbrace: yyDollar[6].tok.Pos}
		}
	case 28:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:139
		{
			yyVAL.stmt = &SoaDecl{PublicPos: optPos(yyDollar[1].optTok), Keyword: yyDollar[2].tok.Pos, Name: ident(yyDollar[3].tok), Type: yyDollar[5].typ, Options: yyDollar[6].opts, Semi: yyDollar[7].tok.Pos}
		}
	case 29:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser.y:140
		{
			yyVAL.stmt = &SoaDecl{PublicPos: optPos(yyDollar[1].optTok), Keyword: yyDollar[2].tok.Pos, Const: true, Name: ident(yyDollar[4].tok), Type: yyDollar[6].typ, Init: yyDollar[8].expr, Options: yyDollar[9].opts, Semi: yyDollar[10].tok.Pos}
		}
	case 30:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:141
		{
			yyVAL.stmt = &IncludeDecl{Include: yyDollar[1].tok.Pos, Kind: yyDollar[2].ident, Path: strLit(yyDollar[4].tok), Rparen: yyDollar[5].tok.Pos, Options: yyDollar[6].opts, Semi: yyDollar[7].tok.Pos}
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:142
		{
			yyVAL.stmt = &ScopeLabel{Keyword: yyDollar[1].tok.Pos, Public: true, Colon: yyDollar[2].tok.Pos}
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:143
		{
			yyVAL.stmt = &ScopeLabel{Keyword: yyDollar[1].tok.Pos, Public: false, Colon: yyDollar[2].tok.Pos}
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:144
		{
			yyVAL.stmt = &PlacementBlock{Keyword: ident(yyDollar[1].tok), Body: yyDollar[2].block, Options: yyDollar[3].opts, Semi: yyDollar[4].tok.Pos}
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:145
		{
			yyVAL.stmt = yyDollar[1].block
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:146
		{
			yyVAL.stmt = &EmptyStmt{Semi: yyDollar[1].tok.Pos}
		}
	case 36:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:149
		{
			yyVAL.fields = []*FieldDecl{}
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:150
		{
			yyVAL.fields = append(yyDollar[1].fields, yyDollar[2].field)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:151
		{
			yyVAL.field = &FieldDecl{Name: ident(yyDollar[1].tok), Type: yyDollar[3].typ, Semi: yyDollar[4].tok.Pos}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:154
		{
			yyVAL.slit = &StructLit{Type: &NamedType{Name: ident(yyDollar[1].tok)}, Lbrace: yyDollar[2].tok.Pos, Fields: yyDollar[3].inits, Rbrace: yyDollar[4].tok.Pos}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:155
		{
			yyVAL.slit = &StructLit{Lbrace: yyDollar[1].tok.Pos, Fields: yyDollar[2].inits, Rbrace: yyDollar[3].tok.Pos}
		}
	case 41:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:156
		{
			yyVAL.inits = []*FieldInit{}
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:157
		{
			yyVAL.inits = yyDollar[1].inits
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:158
		{
			yyVAL.inits = yyDollar[1].inits
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:159
		{
			yyVAL.inits = []*FieldInit{yyDollar[1].init}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:160
		{
			yyVAL.inits = append(yyDollar[1].inits, yyDollar[3].init)
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:161
		{
			yyVAL.init = &FieldInit{Key: ident(yyDollar[1].tok), Colon: yyDollar[2].tok.Pos, Value: yyDollar[3].expr}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:162
		{
			yyVAL.init = &FieldInit{Value: yyDollar[1].expr}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:165
		{
			yyVAL.expr = yyDollar[1].slit
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:166
		{
			yyVAL.exprs = []Expr{yyDollar[1].expr}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:167
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 52:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:170
		{
			yyVAL.stmt = nil
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:171
		{
			yyVAL.stmt = &VarDecl{Keyword: yyDollar[1].tok.Pos, Specs: yyDollar[2].specs}
		}
	case 55:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:174
		{
			yyVAL.stmt = nil
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:177
		{
			yyVAL.stmt = &ExprStmt{X: yyDollar[1].expr}
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:180
		{
			yyVAL.stmt = &IncDecStmt{X: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: Inc}
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:181
		{
			yyVAL.stmt = &IncDecStmt{X: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: Dec}
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:182
		{
			yyVAL.stmt = &IncDecStmt{X: yyDollar[2].expr, OpPos: yyDollar[1].tok.Pos, Op: Inc, Prefix: true}
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:183
		{
			yyVAL.stmt = &IncDecStmt{X: yyDollar[2].expr, OpPos: yyDollar[1].tok.Pos, Op: Dec, Prefix: true}
		}
	case 63:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:185
		{
			yyVAL.optTok = nil
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:186
		{
			t := yyDollar[1].tok
			yyVAL.optTok = &t
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:189
		{
			yyVAL.use = &UseDecl{Module: ident(yyDollar[1].tok), As: yyDollar[2].ident}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:190
		{
			yyVAL.use = &UseDecl{Star: yyDollar[1].tok.Pos, FromAll: true, Module: ident(yyDollar[3].tok)}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:191
		{
			yyVAL.use = &UseDecl{Names: yyDollar[1].idents, Module: ident(yyDollar[3].tok)}
		}
	case 68:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:193
		{
			yyVAL.ident = nil
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:194
		{
			yyVAL.ident = ident(yyDollar[2].tok)
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:196
		{
			yyVAL.idents = []*Ident{ident(yyDollar[1].tok)}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:197
		{
			yyVAL.idents = append(yyDollar[1].idents, ident(yyDollar[3].tok))
		}
	case 72:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:199
		{
			yyVAL.ident = nil
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:200
		{
			yyVAL.ident = ident(yyDollar[1].tok)
		}
	case 74:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:202
		{
			yyVAL.deflt = nil
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:203
		{
			yyVAL.deflt = &DefaultClause{Default: yyDollar[1].tok.Pos, Colon: yyDollar[2].tok.Pos, Body: yyDollar[3].stmts}
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:205
		{
			yyVAL.cases = append(yyDollar[1].cases, yyDollar[2].kase)
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:206
		{
			yyVAL.cases = []*CaseClause{yyDollar[1].kase}
		}
	case 78:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:209
		{
			yyVAL.kase = &CaseClause{Case: yyDollar[1].tok.Pos, Values: yyDollar[2].exprs, Colon: yyDollar[3].tok.Pos, Body: yyDollar[4].stmts}
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:211
		{
			yyVAL.fbody = funcBody{Block: yyDollar[1].block}
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:212
		{
			yyVAL.fbody = funcBody{Semi: yyDollar[1].tok.Pos}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:214
		{
			yyVAL.block = &Block{Lbrace: yyDollar[1].tok.Pos, Stmts: yyDollar[2].stmts, Rbrace: yyDollar[3].tok.Pos}
		}
	case 82:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:216
		{
			yyVAL.block = nil
		}
	case 84:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:219
		{
			yyVAL.stmt = nil
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:220
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 86:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:221
		{
			yyVAL.stmt = &IfStmt{If: yyDollar[1].tok.Pos, IsElsif: true, Lparen: yyDollar[2].tok.Pos, Cond: yyDollar[3].expr, Rparen: yyDollar[4].tok.Pos, Then: yyDollar[5].stmt, Else: yyDollar[6].stmt}
		}
	case 87:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:225
		{
			yyVAL.expr = nil
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:228
		{
			yyVAL.expr = &ParenExpr{Lparen: yyDollar[1].tok.Pos, X: yyDollar[2].expr, Rparen: yyDollar[3].tok.Pos}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:229
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:230
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: Assign, Rhs: yyDollar[3].expr}
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:231
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: Assign, Rhs: yyDollar[3].slit}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:232
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:233
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:234
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:235
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:236
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:237
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:238
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:239
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:240
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:241
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:242
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: AddEq, Rhs: yyDollar[3].expr}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:243
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: SubEq, Rhs: yyDollar[3].expr}
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:244
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: MulEq, Rhs: yyDollar[3].expr}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:245
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: DivEq, Rhs: yyDollar[3].expr}
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:246
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: ModEq, Rhs: yyDollar[3].expr}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:247
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: AndEq, Rhs: yyDollar[3].expr}
		}
	case 109:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:248
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: OrEq, Rhs: yyDollar[3].expr}
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:249
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: XorEq, Rhs: yyDollar[3].expr}
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:250
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: ShlEq, Rhs: yyDollar[3].expr}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:251
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: ShrEq, Rhs: yyDollar[3].expr}
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:252
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:253
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:254
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:255
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:256
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:257
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:258
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:259
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 121:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:260
		{
			yyVAL.expr = &CastExpr{Lt: yyDollar[1].tok.Pos, Type: yyDollar[2].typ, Gt: yyDollar[3].tok.Pos, X: yyDollar[4].expr}
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:261
		{
			yyVAL.expr = &CastExpr{Kind: CastAs, X: yyDollar[1].expr, As: yyDollar[2].tok.Pos, Type: yyDollar[3].typ}
		}
	case 123:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:262
		{
			yyVAL.expr = &CastExpr{Kind: CastBit, Bitcast: yyDollar[1].tok.Pos, Lt: yyDollar[2].tok.Pos, Type: yyDollar[3].typ, Gt: yyDollar[4].tok.Pos, Lparen: yyDollar[5].tok.Pos, X: yyDollar[6].expr, Rparen: yyDollar[7].tok.Pos}
		}
	case 124:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:263
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 125:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:264
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 126:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:265
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 127:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:266
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:267
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 129:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:268
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 130:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:269
		{
			yyVAL.expr = &CallExpr{Fun: yyDollar[1].expr, Lparen: yyDollar[2].tok.Pos, Args: yyDollar[3].alist.exprs, Comma: yyDollar[3].alist.comma, Rparen: yyDollar[4].tok.Pos, Block: yyDollar[5].block}
		}
	case 131:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:270
		{
			yyVAL.expr = &IndexExpr{X: yyDollar[1].expr, Lbrack: yyDollar[2].tok.Pos, Index: yyDollar[3].expr, Rbrack: yyDollar[4].tok.Pos}
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:271
		{
			yyVAL.expr = &ArrayLit{Lbrack: yyDollar[1].tok.Pos, Elems: []Expr{}, Rbrack: yyDollar[2].tok.Pos}
		}
	case 133:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:272
		{
			yyVAL.expr = &ArrayLit{Lbrack: yyDollar[1].tok.Pos, Elems: yyDollar[2].exprs, Rbrack: yyDollar[3].tok.Pos}
		}
	case 134:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:273
		{
			yyVAL.expr = &ArrayLit{Lbrack: yyDollar[1].tok.Pos, Elems: yyDollar[2].exprs, Comma: yyDollar[3].tok.Pos, Rbrack: yyDollar[4].tok.Pos}
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:274
		{
			yyVAL.expr = yyDollar[1].slit
		}
	case 136:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:275
		{
			yyVAL.expr = &SizeofExpr{Sizeof: yyDollar[1].tok.Pos, Lparen: yyDollar[2].tok.Pos, Type: yyDollar[3].typ, Rparen: yyDollar[4].tok.Pos}
		}
	case 137:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:276
		{
			yyVAL.expr = &IncbinExpr{Incbin: yyDollar[1].tok.Pos, Path: strLit(yyDollar[3].tok), Rparen: yyDollar[4].tok.Pos}
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:277
		{
			yyVAL.expr = &LambdaExpr{Arrow: yyDollar[1].tok.Pos, Type: yyDollar[2].typ, Body: yyDollar[3].fbody.Block, Semi: yyDollar[3].fbody.Semi}
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:278
		{
			yyVAL.expr = &IntLit{ValuePos: yyDollar[1].tok.Pos, Value: yyDollar[1].tok.Int, Text: yyDollar[1].tok.Text}
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:279
		{
			yyVAL.expr = &BoolLit{ValuePos: yyDollar[1].tok.Pos, Value: true}
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:280
		{
			yyVAL.expr = &BoolLit{ValuePos: yyDollar[1].tok.Pos, Value: false}
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:281
		{
			yyVAL.expr = &NullLit{ValuePos: yyDollar[1].tok.Pos}
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:282
		{
			yyVAL.expr = ident(yyDollar[1].tok)
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:283
		{
			yyVAL.expr = strLit(yyDollar[1].tok)
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:285
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:286
		{
			yyVAL.exprs = []Expr{yyDollar[1].expr}
		}
	case 147:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:289
		{
			yyVAL.alist = argList{exprs: []Expr{}}
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:290
		{
			yyVAL.alist = argList{exprs: yyDollar[1].exprs}
		}
	case 149:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:291
		{
			yyVAL.alist = argList{exprs: yyDollar[1].exprs, comma: yyDollar[2].tok.Pos}
		}
	case 150:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:295
		{
			yyVAL.opts = nil
		}
	case 152:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:297
		{
			yyVAL.opts = &Options{Keyword: yyDollar[1].tok.Pos, Entries: yyDollar[3].optents, Rparen: yyDollar[4].tok.Pos}
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:300
		{
			yyVAL.optents = append(yyDollar[1].optents, yyDollar[3].optents...)
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:302
		{
			yyVAL.optents = []*OptionEntry{{Key: ident(yyDollar[1].tok), Value: yyDollar[3].expr}}
		}
	case 157:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:306
		{
			yyVAL.specs = []*VarSpec{}
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:308
		{
			yyVAL.specs = append(yyDollar[1].specs, yyDollar[3].spec)
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:309
		{
			yyVAL.specs = []*VarSpec{yyDollar[1].spec}
		}
	case 161:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:311
		{
			yyVAL.spec = &VarSpec{Name: ident(yyDollar[1].tok), Type: yyDollar[3].typ, Init: yyDollar[4].expr, Options: yyDollar[5].opts}
		}
	case 162:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:312
		{
			yyVAL.spec = &VarSpec{Name: ident(yyDollar[1].tok), Init: yyDollar[3].expr, Options: yyDollar[4].opts}
		}
	case 163:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:314
		{
			yyVAL.expr = nil
		}
	case 164:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:315
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 165:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:316
		{
			yyVAL.expr = yyDollar[2].slit
		}
	case 168:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:324
		{
			yyVAL.typ = &PointerType{Star: yyDollar[1].tok.Pos, Elem: yyDollar[2].typ}
		}
	case 169:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:325
		{
			yyVAL.typ = &ArrayType{Lbrack: yyDollar[1].tok.Pos, Len: yyDollar[2].expr, Rbrack: yyDollar[3].tok.Pos, Elem: yyDollar[4].typ}
		}
	case 170:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:326
		{
			yyVAL.typ = &ArrayType{Lbrack: yyDollar[1].tok.Pos, Rbrack: yyDollar[2].tok.Pos, Elem: yyDollar[3].typ}
		}
	case 171:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:327
		{
			yyVAL.typ = &FuncType{Fn: yyDollar[1].tok.Pos, Lparen: yyDollar[2].tok.Pos, Params: yyDollar[3].params, Rparen: yyDollar[4].tok.Pos, Result: yyDollar[6].typ}
		}
	case 172:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:328
		{
			yyVAL.typ = &FuncType{Far: true, Fn: yyDollar[1].tok.Pos, Lparen: yyDollar[2].tok.Pos, Params: yyDollar[3].params, Rparen: yyDollar[4].tok.Pos, Result: yyDollar[6].typ}
		}
	case 173:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:331
		{
			yyVAL.typ = &PointerType{Star: yyDollar[1].tok.Pos, Elem: yyDollar[2].typ}
		}
	case 174:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:332
		{
			yyVAL.typ = &NamedType{Module: ident(yyDollar[1].tok), Name: ident(yyDollar[3].tok)}
		}
	case 175:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:333
		{
			yyVAL.typ = &ArrayType{Lbrack: yyDollar[1].tok.Pos, Len: yyDollar[2].expr, Rbrack: yyDollar[3].tok.Pos, Elem: yyDollar[4].typ}
		}
	case 176:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:334
		{
			yyVAL.typ = &ArrayType{Lbrack: yyDollar[1].tok.Pos, Rbrack: yyDollar[2].tok.Pos, Elem: yyDollar[3].typ}
		}
	case 177:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:335
		{
			yyVAL.typ = &FuncType{Fn: yyDollar[1].tok.Pos, Lparen: yyDollar[2].tok.Pos, Params: yyDollar[3].params, Rparen: yyDollar[4].tok.Pos, Result: yyDollar[6].typ}
		}
	case 178:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:336
		{
			yyVAL.typ = &FuncType{Far: true, Fn: yyDollar[1].tok.Pos, Lparen: yyDollar[2].tok.Pos, Params: yyDollar[3].params, Rparen: yyDollar[4].tok.Pos, Result: yyDollar[6].typ}
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:337
		{
			yyVAL.typ = &NamedType{Name: ident(yyDollar[1].tok)}
		}
	case 180:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:339
		{
			yyVAL.typ = &NamedType{Module: ident(yyDollar[1].tok), Name: ident(yyDollar[3].tok)}
		}
	case 181:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:340
		{
			yyVAL.typ = &ArrayType{Elem: yyDollar[1].typ, Lbrack: yyDollar[2].tok.Pos, Len: yyDollar[3].expr, Rbrack: yyDollar[4].tok.Pos}
		}
	case 182:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:341
		{
			yyVAL.typ = &ArrayType{Elem: yyDollar[1].typ, Lbrack: yyDollar[2].tok.Pos, Rbrack: yyDollar[3].tok.Pos}
		}
	case 183:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:342
		{
			yyVAL.typ = &PointerType{Elem: yyDollar[1].typ, Star: yyDollar[2].tok.Pos}
		}
	case 184:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:343
		{
			yyVAL.typ = &FuncType{Result: yyDollar[1].typ, Lparen: yyDollar[2].tok.Pos, Params: yyDollar[3].params, Rparen: yyDollar[4].tok.Pos}
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:344
		{
			yyVAL.typ = &NamedType{Name: ident(yyDollar[1].tok)}
		}
	case 186:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:346
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:347
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 188:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:348
		{
			yyVAL.params = []*Param{}
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:350
		{
			yyVAL.param = &Param{Type: yyDollar[1].typ}
		}
	case 190:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:351
		{
			yyVAL.param = &Param{Name: ident(yyDollar[1].tok), Type: yyDollar[3].typ}
		}
	}
	goto yystack /* stack new state and value */
}
