// Code generated by goyacc -o parser.go -p yy parser.y. DO NOT EDIT.

//line parser.y:13
package syntax

import __yyfmt__ "fmt"

//line parser.y:13

//line parser.y:16
type yySymType struct {
	yys     int
	tok     Token
	stmt    Stmt
	stmts   []Stmt
	expr    Expr
	exprs   []Expr
	typ     TypeExpr
	spec    *VarSpec
	specs   []*VarSpec
	opts    *Options
	optents []*OptionEntry
	params  []*Param
	param   *Param
	cases   []*CaseClause
	kase    *CaseClause
	deflt   *DefaultClause
	block   *Block
	fbody   funcBody
	ident   *Ident
	idents  []*Ident
	use     *UseDecl
	optTok  *Token
}

const NUMBER = 57346
const IDENT = 57347
const STRING = 57348
const kINCLUDE = 57349
const kFUNCTION = 57350
const kCONST = 57351
const kVAR = 57352
const kOPTIONS = 57353
const kIF = 57354
const kELSE = 57355
const kELSIF = 57356
const kLOOP = 57357
const kWHILE = 57358
const kFOR = 57359
const kRETURN = 57360
const kBREAK = 57361
const kCONTINUE = 57362
const kINCBIN = 57363
const kSWITCH = 57364
const kCASE = 57365
const kDEFAULT = 57366
const kUSE = 57367
const kAS = 57368
const kFROM = 57369
const kPUBLIC = 57370
const kPRIVATE = 57371
const LEQ = 57372
const GEQ = 57373
const EQEQ = 57374
const ADDEQ = 57375
const SUBEQ = 57376
const NEQ = 57377
const ARROW = 57378
const LSHIFT = 57379
const RSHIFT = 57380
const ANDAND = 57381
const OROR = 57382
const UMINUS = 57383
const NO_ELSE = 57384

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMBER",
	"IDENT",
	"STRING",
	"kINCLUDE",
	"kFUNCTION",
	"kCONST",
	"kVAR",
	"kOPTIONS",
	"kIF",
	"kELSE",
	"kELSIF",
	"kLOOP",
	"kWHILE",
	"kFOR",
	"kRETURN",
	"kBREAK",
	"kCONTINUE",
	"kINCBIN",
	"kSWITCH",
	"kCASE",
	"kDEFAULT",
	"kUSE",
	"kAS",
	"kFROM",
	"kPUBLIC",
	"kPRIVATE",
	"LEQ",
	"GEQ",
	"EQEQ",
	"ADDEQ",
	"SUBEQ",
	"NEQ",
	"ARROW",
	"LSHIFT",
	"RSHIFT",
	"ANDAND",
	"OROR",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"';'",
	"':'",
	"'<'",
	"'>'",
	"'['",
	"']'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'&'",
	"'|'",
	"'^'",
	"'='",
	"','",
	"'.'",
	"'!'",
	"UMINUS",
	"NO_ELSE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:244

//line yacctab:1
var yyExca = [...]int16{
	-1, 0,
	1, 3,
	-2, 26,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 3,
	1, 2,
	44, 2,
	-2, 26,
	-1, 36,
	44, 3,
	-2, 26,
	-1, 101,
	45, 31,
	-2, 33,
	-1, 240,
	44, 38,
	-2, 26,
	-1, 241,
	23, 41,
	24, 41,
	44, 41,
	-2, 26,
}

const yyPrivate = 57344

const yyLast = 858

var yyAct = [...]uint8{
	15, 210, 4, 20, 143, 89, 37, 5, 176, 215,
	175, 3, 148, 96, 49, 161, 74, 16, 152, 236,
	181, 207, 155, 81, 75, 84, 85, 86, 87, 88,
	90, 200, 82, 141, 139, 151, 52, 152, 95, 166,
	92, 235, 137, 104, 101, 106, 138, 222, 162, 201,
	152, 109, 206, 110, 111, 112, 113, 114, 115, 116,
	117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
	127, 128, 129, 130, 131, 90, 133, 230, 98, 168,
	132, 140, 202, 157, 36, 35, 145, 32, 33, 34,
	17, 141, 102, 153, 35, 7, 144, 141, 8, 9,
	10, 13, 11, 12, 30, 14, 154, 182, 80, 79,
	108, 18, 19, 164, 76, 139, 32, 33, 34, 31,
	47, 46, 234, 137, 22, 150, 36, 138, 21, 36,
	23, 195, 29, 30, 26, 25, 27, 171, 172, 28,
	209, 198, 178, 180, 139, 24, 139, 224, 31, 179,
	105, 136, 137, 22, 137, 185, 138, 156, 138, 23,
	134, 29, 184, 26, 25, 27, 183, 194, 28, 93,
	91, 192, 197, 193, 24, 72, 73, 50, 45, 74,
	44, 43, 42, 204, 2, 160, 159, 75, 74, 54,
	55, 56, 57, 58, 203, 187, 75, 216, 228, 52,
	56, 57, 58, 208, 216, 211, 212, 221, 52, 35,
	170, 219, 218, 142, 225, 83, 208, 90, 177, 223,
	217, 94, 229, 208, 227, 232, 139, 220, 36, 174,
	145, 231, 149, 191, 137, 190, 189, 239, 138, 188,
	97, 144, 242, 37, 37, 244, 243, 240, 241, 208,
	40, 39, 38, 237, 70, 71, 66, 64, 65, 67,
	107, 72, 73, 62, 63, 74, 238, 41, 99, 78,
	205, 68, 69, 75, 186, 54, 55, 56, 57, 58,
	59, 60, 61, 53, 147, 52, 70, 71, 66, 64,
	65, 67, 146, 72, 73, 62, 63, 74, 233, 48,
	196, 214, 226, 68, 69, 75, 103, 54, 55, 56,
	57, 58, 59, 60, 61, 53, 77, 52, 70, 71,
	66, 64, 65, 67, 158, 72, 73, 62, 63, 74,
	100, 35, 6, 1, 0, 68, 69, 75, 0, 54,
	55, 56, 57, 58, 59, 60, 61, 53, 213, 52,
	70, 71, 66, 64, 65, 67, 0, 72, 73, 62,
	63, 74, 0, 0, 0, 0, 0, 68, 69, 75,
	0, 54, 55, 56, 57, 58, 59, 60, 61, 53,
	0, 52, 70, 71, 66, 64, 65, 67, 0, 72,
	73, 62, 63, 74, 0, 0, 0, 0, 0, 68,
	69, 75, 199, 54, 55, 56, 57, 58, 59, 60,
	61, 53, 0, 52, 70, 71, 66, 64, 65, 67,
	0, 72, 73, 62, 63, 74, 0, 0, 0, 0,
	0, 68, 69, 75, 169, 54, 55, 56, 57, 58,
	59, 60, 61, 53, 0, 52, 70, 71, 66, 64,
	65, 67, 0, 72, 73, 62, 63, 74, 167, 0,
	0, 0, 0, 68, 69, 75, 0, 54, 55, 56,
	57, 58, 59, 60, 61, 53, 0, 52, 70, 71,
	66, 64, 65, 67, 0, 72, 73, 62, 63, 74,
	165, 0, 0, 0, 0, 68, 69, 75, 0, 54,
	55, 56, 57, 58, 59, 60, 61, 53, 0, 52,
	70, 71, 66, 64, 65, 67, 0, 72, 73, 62,
	63, 74, 163, 0, 0, 0, 0, 68, 69, 75,
	0, 54, 55, 56, 57, 58, 59, 60, 61, 53,
	0, 52, 70, 71, 66, 64, 65, 67, 0, 72,
	73, 62, 63, 74, 135, 0, 0, 0, 0, 68,
	69, 75, 0, 54, 55, 56, 57, 58, 59, 60,
	61, 53, 0, 52, 70, 71, 66, 64, 65, 67,
	0, 72, 73, 62, 63, 74, 0, 0, 0, 51,
	0, 68, 69, 75, 0, 54, 55, 56, 57, 58,
	59, 60, 61, 53, 0, 52, 70, 71, 66, 64,
	65, 67, 0, 72, 73, 62, 63, 74, 0, 0,
	0, 0, 0, 68, 69, 75, 0, 54, 55, 56,
	57, 58, 59, 60, 61, 53, 0, 52, 70, 71,
	66, 0, 0, 67, 0, 72, 73, 62, 0, 74,
	0, 0, 0, 0, 0, 68, 69, 75, 0, 54,
	55, 56, 57, 58, 59, 60, 61, 0, 0, 52,
	70, 71, 66, 0, 0, 67, 0, 72, 73, 0,
	0, 74, 0, 0, 0, 0, 0, 68, 69, 75,
	0, 54, 55, 56, 57, 58, 59, 60, 61, 0,
	0, 52, 70, 71, 66, 0, 0, 67, 0, 72,
	73, 0, 0, 74, 0, 0, 0, 0, 0, 68,
	69, 75, 0, 54, 55, 56, 57, 58, 59, 0,
	61, 0, 0, 52, 70, 71, 66, 0, 0, 67,
	0, 72, 73, 0, 0, 74, 0, 0, 0, 0,
	0, 68, 69, 75, 0, 54, 55, 56, 57, 58,
	59, 70, 71, 66, 0, 52, 67, 0, 72, 73,
	0, 0, 74, 32, 33, 34, 0, 0, 68, 69,
	75, 0, 54, 55, 56, 57, 58, 74, 0, 0,
	30, 0, 52, 0, 0, 75, 0, 54, 55, 56,
	57, 58, 0, 0, 0, 31, 0, 52, 0, 0,
	22, 0, 0, 0, 0, 0, 23, 0, 29, 173,
	26, 25, 27, 0, 0, 28, 70, 71, 0, 0,
	0, 24, 0, 72, 73, 0, 0, 74, 0, 0,
	0, 0, 0, 68, 69, 75, 0, 54, 55, 56,
	57, 58, 0, 0, 0, 0, 0, 52,
}

var yyPact = [...]int16{
	83, -32768, -32768, 83, -32768, -32768, 242, 141, 140, 139,
	137, 76, 75, 112, 136, 544, 69, 264, 63, 62,
	-32768, -32768, 112, 210, 112, 112, 112, 112, 112, 112,
	129, 210, -32768, -32768, -32768, 128, 83, -32768, 235, 235,
	263, 39, 112, 108, 112, 255, -32768, -32768, 65, 576,
	112, -32768, 112, 112, 112, 112, 112, 112, 112, 112,
	112, 112, 112, 112, 112, 112, 112, 112, 112, 112,
	112, 112, 112, 112, 112, 112, -32768, 119, -32768, -32768,
	-32768, 512, 103, -32768, -25, -25, -25, -25, -25, 31,
	576, 207, 185, 227, 81, -10, -32768, 47, -23, 116,
	38, 160, 158, -12, 480, 83, 448, -21, -32768, 416,
	-32768, 576, 147, 147, -25, -25, -25, 731, 672, 704,
	640, 608, 576, 576, 796, 796, 138, 138, 138, 138,
	746, 746, 37, 384, 204, -32768, 112, 769, -32768, 213,
	-32768, 112, 107, -32768, -32768, -32768, 101, -40, -32768, 61,
	-32768, -32768, 235, 210, 112, -32768, 235, -32768, -32768, 234,
	231, 230, 228, 83, -32768, 83, 112, 88, 86, -32768,
	99, 138, 352, -32768, -11, -32768, 105, 36, 576, -32768,
	-32768, 227, 112, -32768, -7, 320, 98, -42, -32768, -32768,
	-32768, -32768, 192, -32768, 288, 181, -32768, -32768, 198, -32768,
	-32768, 213, 210, -32768, 576, 198, 112, -32768, -32768, 1,
	-32768, 83, 106, 112, 174, -32768, 112, 32, -32768, 105,
	-32768, 576, 210, -32768, 112, 256, 78, -32768, -5, -27,
	-32768, 74, 224, 86, -32768, 83, 83, 41, 83, -32768,
	83, 83, -32768, 192, -32768,
}

var yyPgo = [...]int16{
	0, 333, 184, 11, 2, 7, 1, 332, 330, 324,
	316, 306, 302, 301, 9, 3, 300, 4, 299, 0,
	5, 21, 17, 292, 284, 12, 274, 38, 13, 270,
	8, 229, 10,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 4, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 7, 7, 8, 8,
	8, 9, 9, 11, 11, 10, 10, 12, 12, 13,
	13, 14, 17, 17, 15, 16, 16, 6, 6, 6,
	18, 18, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 20,
	20, 20, 21, 21, 22, 23, 24, 24, 25, 26,
	26, 27, 27, 28, 28, 29, 29, 30, 30, 30,
	30, 30, 31, 31, 31, 32, 32,
}

var yyR2 = [...]int8{
	0, 1, 1, 0, 2, 1, 1, 4, 4, 6,
	4, 5, 9, 2, 2, 3, 8, 2, 10, 2,
	4, 7, 2, 2, 1, 1, 0, 1, 2, 3,
	3, 0, 2, 1, 3, 0, 1, 0, 3, 2,
	1, 4, 1, 1, 3, 0, 1, 0, 2, 6,
	0, 1, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
	2, 5, 4, 3, 4, 3, 1, 1, 1, 3,
	1, 0, 0, 1, 4, 1, 3, 1, 3, 0,
	1, 3, 1, 5, 4, 0, 2, 4, 3, 2,
	4, 1, 3, 1, 0, 1, 3,
}

var yyChk = [...]int16{
	-32768, -1, -2, -3, -4, -5, -7, 12, 15, 16,
	17, 19, 20, 18, 22, -19, -22, 7, 28, 29,
	-15, 45, 41, 47, 62, 52, 51, 53, 56, 49,
	21, 36, 4, 5, 6, 11, 43, -4, 10, 9,
	8, 25, 41, 41, 41, 41, 45, 45, -18, -19,
	41, 45, 61, 59, 51, 52, 53, 54, 55, 56,
	57, 58, 39, 40, 33, 34, 32, 35, 47, 48,
	30, 31, 37, 38, 41, 49, 45, -10, 5, 46,
	46, -19, -30, 5, -19, -19, -19, -19, -19, -20,
	-19, 41, -30, 41, -2, -27, -28, 5, -27, 5,
	-8, 5, 53, -11, -19, 42, -19, 5, 45, -19,
	-19, -19, -19, -19, -19, -19, -19, -19, -19, -19,
	-19, -19, -19, -19, -19, -19, -19, -19, -19, -19,
	-19, -19, -20, -19, 41, 42, 48, 49, 53, 41,
	50, 60, 6, -17, -15, 45, -23, -24, -25, 5,
	44, 45, 60, 46, 59, 45, 41, 45, -9, 26,
	27, 27, 60, 42, -5, 42, 60, 42, 42, 50,
	6, -19, -19, 50, -31, -32, -30, 5, -19, 42,
	42, 60, 46, -28, -30, -19, -26, -27, 5, 5,
	5, 5, -5, -5, -19, 43, -16, -15, 42, 50,
	42, 60, 46, -25, -19, -29, 59, -21, -22, 42,
	-6, 13, 14, 60, -13, -14, 23, -21, -32, -30,
	-21, -19, 46, -5, 41, -19, -12, -14, 24, -20,
	45, -30, -19, 42, 44, 46, 46, -21, 42, -15,
	-3, -3, -17, -5, -6,
}

var yyDef = [...]int8{
	-2, -2, 1, -2, 5, 6, 0, 0, 0, 0,
	0, 0, 0, 50, 0, 0, 0, 35, 27, 0,
	24, 25, 0, 0, 0, 0, 0, 0, 0, 91,
	0, 0, 86, 87, 88, 0, -2, 4, 0, 0,
	0, 0, 0, 0, 0, 0, 13, 14, 0, 51,
	0, 17, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 91, 0, 19, 0, 36, 22,
	23, 0, 0, 111, 76, 77, 78, 79, 80, 0,
	90, 0, 0, 0, 0, 0, 102, 0, 0, 0,
	0, -2, 0, 0, 0, 26, 0, 0, 15, 0,
	53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
	63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
	73, 74, 0, 0, 0, 52, 0, 0, 109, 114,
	83, 0, 0, 85, 42, 43, 0, 95, 97, 0,
	44, 7, 0, 0, 0, 8, 99, 20, 28, 0,
	0, 0, 0, 26, 10, 26, 0, 0, 45, 82,
	0, 75, 0, 108, 0, 113, 115, 111, 89, 84,
	94, 0, 0, 101, 105, 92, 0, 100, 32, 29,
	30, 34, 47, 11, 0, 0, 81, 46, 92, 107,
	110, 0, 0, 96, 98, 92, 0, 104, 93, 0,
	9, 26, 0, 0, 37, 40, 91, 0, 112, 116,
	103, 106, 0, 48, 0, 0, 0, 39, 0, 0,
	21, 92, 0, 0, 16, 26, 26, 0, 26, 12,
	-2, -2, 18, 47, 49,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 62, 3, 3, 3, 55, 56, 3,
	41, 42, 53, 51, 60, 52, 61, 54, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 46, 45,
	47, 59, 48, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 49, 3, 50, 58, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 43, 57, 44,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 63,
	64,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:87
		{
			yylex.(*yyLexAdapter).result = yyDollar[1].stmts
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:93
		{
			yyVAL.stmts = []Stmt{}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:95
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:96
		{
			yyVAL.stmts = []Stmt{yyDollar[1].stmt}
		}
	case 7:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:100
		{
			yyVAL.stmt = &VarDecl{PublicPos: optPos(yyDollar[1].optTok), Keyword: yyDollar[2].tok.Pos, Specs: yyDollar[3].specs, Semi: yyDollar[4].tok.Pos}
		}
	case 8:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:101
		{
			yyVAL.stmt = &VarDecl{PublicPos: optPos(yyDollar[1].optTok), Keyword: yyDollar[2].tok.Pos, Const: true, Specs: yyDollar[3].specs, Semi: yyDollar[4].tok.Pos}
		}
	case 9:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:102
		{
			yyVAL.stmt = &IfStmt{If: yyDollar[1].tok.Pos, Lparen: yyDollar[2].tok.Pos, Cond: yyDollar[3].expr, Rparen: yyDollar[4].tok.Pos, Then: yyDollar[5].stmt, Else: yyDollar[6].stmt}
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:103
		{
			yyVAL.stmt = &LoopStmt{Loop: yyDollar[1].tok.Pos, Rparen: yyDollar[3].tok.Pos, Body: yyDollar[4].stmt}
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:104
		{
			yyVAL.stmt = &WhileStmt{While: yyDollar[1].tok.Pos, Cond: yyDollar[3].expr, Rparen: yyDollar[4].tok.Pos, Body: yyDollar[5].stmt}
		}
	case 12:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.y:105
		{
			yyVAL.stmt = &ForStmt{For: yyDollar[1].tok.Pos, Var: ident(yyDollar[3].tok), From: yyDollar[5].expr, To: yyDollar[7].expr, Rparen: yyDollar[8].tok.Pos, Body: yyDollar[9].block}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:106
		{
			yyVAL.stmt = &BreakStmt{Keyword: yyDollar[1].tok.Pos, Semi: yyDollar[2].tok.Pos}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:107
		{
			yyVAL.stmt = &ContinueStmt{Keyword: yyDollar[1].tok.Pos, Semi: yyDollar[2].tok.Pos}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:108
		{
			yyVAL.stmt = &ReturnStmt{Return: yyDollar[1].tok.Pos, Value: yyDollar[2].expr, Semi: yyDollar[3].tok.Pos}
		}
	case 16:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.y:109
		{
			yyVAL.stmt = &SwitchStmt{Switch: yyDollar[1].tok.Pos, Tag: yyDollar[3].expr, Lbrace: yyDollar[5].tok.Pos, Cases: yyDollar[6].cases, Default: yyDollar[7].deflt, Rbrace: yyDollar[8].tok.Pos}
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:110
		{
			yyVAL.stmt = &ExprStmt{X: yyDollar[1].expr, Semi: yyDollar[2].tok.Pos}
		}
	case 18:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser.y:112
		{
			yyVAL.stmt = funcDecl(yyDollar[1].optTok, yyDollar[2].tok, yyDollar[3].tok, yyDollar[5].specs, yyDollar[8].typ, yyDollar[9].opts, yyDollar[10].fbody)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:113
		{
			yyVAL.stmt = &OptionsStmt{Options: yyDollar[1].opts, Semi: yyDollar[2].tok.Pos}
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:114
		{
			u := yyDollar[3].use
			u.PublicPos = optPos(yyDollar[1].optTok)
			u.Use = yyDollar[2].tok.Pos
			u.Semi = yyDollar[4].tok.Pos
			yyVAL.stmt = u
		}
	case 21:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:115
		{
			yyVAL.stmt = &IncludeDecl{Include: yyDollar[1].tok.Pos, Kind: yyDollar[2].ident, Path: strLit(yyDollar[4].tok), Rparen: yyDollar[5].tok.Pos, Options: yyDollar[6].opts, Semi: yyDollar[7].tok.Pos}
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:116
		{
			yyVAL.stmt = &ScopeLabel{Keyword: yyDollar[1].tok.Pos, Public: true, Colon: yyDollar[2].tok.Pos}
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:117
		{
			yyVAL.stmt = &ScopeLabel{Keyword: yyDollar[1].tok.Pos, Public: false, Colon: yyDollar[2].tok.Pos}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:118
		{
			yyVAL.stmt = yyDollar[1].block
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:119
		{
			yyVAL.stmt = &EmptyStmt{Semi: yyDollar[1].tok.Pos}
		}
	case 26:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:121
		{
			yyVAL.optTok = nil
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:122
		{
			t := yyDollar[1].tok
			yyVAL.optTok = &t
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:125
		{
			yyVAL.use = &UseDecl{Module: ident(yyDollar[1].tok), As: yyDollar[2].ident}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:126
		{
			yyVAL.use = &UseDecl{Star: yyDollar[1].tok.Pos, FromAll: true, Module: ident(yyDollar[3].tok)}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:127
		{
			yyVAL.use = &UseDecl{Names: yyDollar[1].idents, Module: ident(yyDollar[3].tok)}
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:129
		{
			yyVAL.ident = nil
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:130
		{
			yyVAL.ident = ident(yyDollar[2].tok)
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:132
		{
			yyVAL.idents = []*Ident{ident(yyDollar[1].tok)}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:133
		{
			yyVAL.idents = append(yyDollar[1].idents, ident(yyDollar[3].tok))
		}
	case 35:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:135
		{
			yyVAL.ident = nil
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:136
		{
			yyVAL.ident = ident(yyDollar[1].tok)
		}
	case 37:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:138
		{
			yyVAL.deflt = nil
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:139
		{
			yyVAL.deflt = &DefaultClause{Default: yyDollar[1].tok.Pos, Colon: yyDollar[2].tok.Pos, Body: yyDollar[3].stmts}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:141
		{
			yyVAL.cases = append(yyDollar[1].cases, yyDollar[2].kase)
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:142
		{
			yyVAL.cases = []*CaseClause{yyDollar[1].kase}
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:144
		{
			yyVAL.kase = &CaseClause{Case: yyDollar[1].tok.Pos, Values: yyDollar[2].exprs, Colon: yyDollar[3].tok.Pos, Body: yyDollar[4].stmts}
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:146
		{
			yyVAL.fbody = funcBody{Block: yyDollar[1].block}
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:147
		{
			yyVAL.fbody = funcBody{Semi: yyDollar[1].tok.Pos}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:149
		{
			yyVAL.block = &Block{Lbrace: yyDollar[1].tok.Pos, Stmts: yyDollar[2].stmts, Rbrace: yyDollar[3].tok.Pos}
		}
	case 45:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:151
		{
			yyVAL.block = nil
		}
	case 47:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:154
		{
			yyVAL.stmt = nil
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:155
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 49:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:156
		{
			yyVAL.stmt = &IfStmt{If: yyDollar[1].tok.Pos, IsElsif: true, Lparen: yyDollar[2].tok.Pos, Cond: yyDollar[3].expr, Rparen: yyDollar[4].tok.Pos, Then: yyDollar[5].stmt, Else: yyDollar[6].stmt}
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:160
		{
			yyVAL.expr = nil
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:163
		{
			yyVAL.expr = &ParenExpr{Lparen: yyDollar[1].tok.Pos, X: yyDollar[2].expr, Rparen: yyDollar[3].tok.Pos}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:164
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:165
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: Assign, Rhs: yyDollar[3].expr}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:166
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:167
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:168
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:169
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:170
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:171
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:172
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:173
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:174
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:175
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:176
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: AddEq, Rhs: yyDollar[3].expr}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:177
		{
			yyVAL.expr = &AssignExpr{Lhs: yyDollar[1].expr, OpPos: yyDollar[2].tok.Pos, Op: SubEq, Rhs: yyDollar[3].expr}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:178
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:179
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:180
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:181
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:182
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:183
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:184
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:185
		{
			yyVAL.expr = binary(yyDollar[1].expr, yyDollar[2].tok, yyDollar[3].expr)
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:186
		{
			yyVAL.expr = &CastExpr{Lt: yyDollar[1].tok.Pos, Type: yyDollar[2].typ, Gt: yyDollar[3].tok.Pos, X: yyDollar[4].expr}
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:187
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:188
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:189
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:190
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:191
		{
			yyVAL.expr = unary(yyDollar[1].tok, yyDollar[2].expr)
		}
	case 81:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:192
		{
			yyVAL.expr = &CallExpr{Fun: yyDollar[1].expr, Lparen: yyDollar[2].tok.Pos, Args: yyDollar[3].exprs, Rparen: yyDollar[4].tok.Pos, Block: yyDollar[5].block}
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:193
		{
			yyVAL.expr = &IndexExpr{X: yyDollar[1].expr, Lbrack: yyDollar[2].tok.Pos, Index: yyDollar[3].expr, Rbrack: yyDollar[4].tok.Pos}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:194
		{
			yyVAL.expr = &ArrayLit{Lbrack: yyDollar[1].tok.Pos, Elems: yyDollar[2].exprs, Rbrack: yyDollar[3].tok.Pos}
		}
	case 84:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:195
		{
			yyVAL.expr = &IncbinExpr{Incbin: yyDollar[1].tok.Pos, Path: strLit(yyDollar[3].tok), Rparen: yyDollar[4].tok.Pos}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:196
		{
			yyVAL.expr = &LambdaExpr{Arrow: yyDollar[1].tok.Pos, Type: yyDollar[2].typ, Body: yyDollar[3].fbody.Block, Semi: yyDollar[3].fbody.Semi}
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:197
		{
			yyVAL.expr = &IntLit{ValuePos: yyDollar[1].tok.Pos, Value: yyDollar[1].tok.Int, Text: yyDollar[1].tok.Text}
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:198
		{
			yyVAL.expr = ident(yyDollar[1].tok)
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:199
		{
			yyVAL.expr = strLit(yyDollar[1].tok)
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:201
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:202
		{
			yyVAL.exprs = []Expr{yyDollar[1].expr}
		}
	case 91:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:203
		{
			yyVAL.exprs = []Expr{}
		}
	case 92:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:207
		{
			yyVAL.opts = nil
		}
	case 94:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:209
		{
			yyVAL.opts = &Options{Keyword: yyDollar[1].tok.Pos, Entries: yyDollar[3].optents, Rparen: yyDollar[4].tok.Pos}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:212
		{
			yyVAL.optents = append(yyDollar[1].optents, yyDollar[3].optents...)
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:214
		{
			yyVAL.optents = []*OptionEntry{{Key: ident(yyDollar[1].tok), Value: yyDollar[3].expr}}
		}
	case 99:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:218
		{
			yyVAL.specs = []*VarSpec{}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:220
		{
			yyVAL.specs = append(yyDollar[1].specs, yyDollar[3].spec)
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:221
		{
			yyVAL.specs = []*VarSpec{yyDollar[1].spec}
		}
	case 103:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:223
		{
			yyVAL.spec = &VarSpec{Name: ident(yyDollar[1].tok), Type: yyDollar[3].typ, Init: yyDollar[4].expr, Options: yyDollar[5].opts}
		}
	case 104:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:224
		{
			yyVAL.spec = &VarSpec{Name: ident(yyDollar[1].tok), Init: yyDollar[3].expr, Options: yyDollar[4].opts}
		}
	case 105:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:226
		{
			yyVAL.expr = nil
		}
	case 106:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:227
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:231
		{
			yyVAL.typ = &ArrayType{Elem: yyDollar[1].typ, Lbrack: yyDollar[2].tok.Pos, Len: yyDollar[3].expr, Rbrack: yyDollar[4].tok.Pos}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:232
		{
			yyVAL.typ = &ArrayType{Elem: yyDollar[1].typ, Lbrack: yyDollar[2].tok.Pos, Rbrack: yyDollar[3].tok.Pos}
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:233
		{
			yyVAL.typ = &PointerType{Elem: yyDollar[1].typ, Star: yyDollar[2].tok.Pos}
		}
	case 110:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:234
		{
			yyVAL.typ = &FuncType{Result: yyDollar[1].typ, Lparen: yyDollar[2].tok.Pos, Params: yyDollar[3].params, Rparen: yyDollar[4].tok.Pos}
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:235
		{
			yyVAL.typ = &NamedType{Name: ident(yyDollar[1].tok)}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:237
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:238
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 114:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:239
		{
			yyVAL.params = []*Param{}
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:241
		{
			yyVAL.param = &Param{Type: yyDollar[1].typ}
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:242
		{
			yyVAL.param = &Param{Name: ident(yyDollar[1].tok), Type: yyDollar[3].typ}
		}
	}
	goto yystack /* stack new state and value */
}
