    ;; this file is generated by fc command
	.list

    ;; options
<%= opt_asm %>

    ;; interrupt vector
	.bank <%= prog_bank_count-1 %>
	.org $FFFA
	.dw interrupt
	.dw start
	.dw interrupt_irq

;;; call subroutine
;;; use 25 cycle
;;; TODO: フレームサイズがが4以下のときは、inx/dexを使って小さくする
call .macro
	txa
	pha
	clc
	adc \2
	tax
	jsr \1
	pla
	tax
	.endm

	;; 
reg = 0							; 汎用レジスタ
S = $80 	       				; フレームスタック
L = $10							; ローカルレジスタメモリ

<%= code_asm %>
<%= chr_asm %>
