// Code generated by goyacc -o parser.go -p fc parser.y. DO NOT EDIT.

//line parser.y:10
package fc

import __yyfmt__ "fmt"

//line parser.y:10

//line parser.y:13
type fcSymType struct {
	yys int
	n   any
}

const NUMBER = 57346
const IDENT = 57347
const STRING = 57348
const kINCLUDE = 57349
const kFUNCTION = 57350
const kCONST = 57351
const kVAR = 57352
const kOPTIONS = 57353
const kIF = 57354
const kELSE = 57355
const kELSIF = 57356
const kLOOP = 57357
const kWHILE = 57358
const kFOR = 57359
const kRETURN = 57360
const kBREAK = 57361
const kCONTINUE = 57362
const kINCBIN = 57363
const kSWITCH = 57364
const kCASE = 57365
const kDEFAULT = 57366
const kUSE = 57367
const kAS = 57368
const kFROM = 57369
const kPUBLIC = 57370
const kPRIVATE = 57371
const LEQ = 57372
const GEQ = 57373
const EQEQ = 57374
const ADDEQ = 57375
const SUBEQ = 57376
const NEQ = 57377
const ARROW = 57378
const LSHIFT = 57379
const RSHIFT = 57380
const ANDAND = 57381
const OROR = 57382
const tID = 57383
const UMINUS = 57384
const NO_ELSE = 57385

var fcToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMBER",
	"IDENT",
	"STRING",
	"kINCLUDE",
	"kFUNCTION",
	"kCONST",
	"kVAR",
	"kOPTIONS",
	"kIF",
	"kELSE",
	"kELSIF",
	"kLOOP",
	"kWHILE",
	"kFOR",
	"kRETURN",
	"kBREAK",
	"kCONTINUE",
	"kINCBIN",
	"kSWITCH",
	"kCASE",
	"kDEFAULT",
	"kUSE",
	"kAS",
	"kFROM",
	"kPUBLIC",
	"kPRIVATE",
	"LEQ",
	"GEQ",
	"EQEQ",
	"ADDEQ",
	"SUBEQ",
	"NEQ",
	"ARROW",
	"LSHIFT",
	"RSHIFT",
	"ANDAND",
	"OROR",
	"tID",
	"'='",
	"'|'",
	"'^'",
	"'&'",
	"'<'",
	"'>'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UMINUS",
	"'.'",
	"'('",
	"'['",
	"NO_ELSE",
	"';'",
	"')'",
	"','",
	"'{'",
	"'}'",
	"':'",
	"'!'",
	"']'",
}

var fcStatenames = [...]string{}

const fcEofCode = 1
const fcErrCode = 2
const fcInitialStackSize = 16

//line parser.y:202

//line yacctab:1
var fcExca = [...]int16{
	-1, 0,
	1, 3,
	-2, 26,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 3,
	1, 2,
	62, 2,
	-2, 26,
	-1, 37,
	62, 3,
	-2, 26,
	-1, 239,
	62, 38,
	-2, 26,
	-1, 240,
	23, 41,
	24, 41,
	62, 41,
	-2, 26,
}

const fcPrivate = 57344

const fcLast = 830

var fcAct = [...]uint8{
	15, 209, 4, 21, 148, 93, 38, 5, 177, 214,
	176, 3, 153, 146, 49, 100, 235, 16, 78, 159,
	146, 206, 234, 233, 85, 145, 88, 89, 90, 91,
	92, 94, 221, 86, 201, 183, 99, 84, 83, 150,
	158, 96, 37, 104, 155, 106, 37, 199, 200, 208,
	192, 109, 157, 110, 111, 112, 113, 114, 115, 116,
	117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
	127, 128, 129, 130, 131, 94, 133, 102, 143, 182,
	132, 167, 146, 144, 142, 160, 150, 157, 156, 37,
	157, 165, 197, 181, 33, 34, 35, 18, 180, 137,
	149, 36, 7, 105, 229, 8, 9, 10, 13, 11,
	12, 31, 14, 163, 36, 17, 195, 108, 19, 20,
	76, 54, 55, 56, 57, 58, 32, 52, 74, 75,
	52, 74, 75, 47, 80, 29, 24, 46, 27, 26,
	28, 172, 205, 173, 223, 23, 30, 179, 22, 161,
	143, 37, 138, 143, 25, 144, 142, 97, 144, 142,
	186, 70, 71, 95, 50, 45, 191, 185, 72, 73,
	189, 194, 190, 184, 44, 43, 42, 68, 69, 54,
	55, 56, 57, 58, 203, 52, 74, 75, 56, 57,
	58, 143, 52, 74, 75, 202, 144, 142, 188, 140,
	80, 2, 143, 136, 207, 135, 220, 144, 142, 79,
	218, 217, 170, 224, 215, 207, 94, 36, 222, 216,
	171, 228, 207, 226, 231, 147, 219, 215, 227, 87,
	230, 210, 211, 41, 40, 39, 238, 178, 154, 98,
	149, 241, 38, 38, 243, 242, 239, 240, 207, 196,
	101, 134, 236, 70, 71, 66, 64, 65, 67, 107,
	72, 73, 62, 63, 103, 53, 60, 61, 59, 68,
	69, 54, 55, 56, 57, 58, 82, 52, 74, 75,
	175, 141, 70, 71, 66, 64, 65, 67, 198, 72,
	73, 62, 63, 204, 53, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 187, 52, 74, 75, 152,
	151, 70, 71, 66, 64, 65, 67, 168, 72, 73,
	62, 63, 48, 53, 60, 61, 59, 68, 69, 54,
	55, 56, 57, 58, 193, 52, 74, 75, 213, 225,
	81, 212, 70, 71, 66, 64, 65, 67, 169, 72,
	73, 62, 63, 77, 53, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 6, 52, 74, 75, 1,
	0, 237, 70, 71, 66, 64, 65, 67, 0, 72,
	73, 62, 63, 0, 53, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 0, 52, 74, 75, 0,
	0, 232, 70, 71, 66, 64, 65, 67, 0, 72,
	73, 62, 63, 0, 53, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 0, 52, 74, 75, 0,
	0, 166, 70, 71, 66, 64, 65, 67, 0, 72,
	73, 62, 63, 0, 53, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 0, 52, 74, 75, 0,
	0, 164, 70, 71, 66, 64, 65, 67, 0, 72,
	73, 62, 63, 0, 53, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 0, 52, 74, 75, 0,
	0, 162, 70, 71, 66, 64, 65, 67, 0, 72,
	73, 62, 63, 0, 53, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 0, 52, 74, 75, 0,
	0, 139, 70, 71, 66, 64, 65, 67, 0, 72,
	73, 62, 63, 36, 53, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 0, 52, 74, 75, 0,
	51, 0, 70, 71, 66, 64, 65, 67, 0, 72,
	73, 62, 63, 0, 53, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 0, 52, 74, 75, 70,
	71, 66, 64, 65, 67, 0, 72, 73, 62, 63,
	0, 53, 60, 61, 59, 68, 69, 54, 55, 56,
	57, 58, 0, 52, 74, 75, 33, 34, 35, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 31, 0, 0, 0, 33, 34, 35,
	0, 0, 0, 0, 0, 0, 0, 0, 32, 0,
	0, 0, 0, 0, 31, 0, 0, 29, 24, 0,
	27, 26, 28, 0, 0, 0, 0, 23, 30, 32,
	0, 0, 0, 0, 0, 0, 25, 174, 29, 24,
	0, 27, 26, 28, 0, 70, 71, 66, 23, 30,
	67, 0, 72, 73, 62, 0, 0, 25, 60, 61,
	59, 68, 69, 54, 55, 56, 57, 58, 0, 52,
	74, 75, 70, 71, 66, 0, 0, 67, 0, 72,
	73, 0, 0, 0, 0, 60, 61, 59, 68, 69,
	54, 55, 56, 57, 58, 0, 52, 74, 75, 70,
	71, 66, 0, 0, 67, 0, 72, 73, 0, 0,
	0, 0, 0, 61, 59, 68, 69, 54, 55, 56,
	57, 58, 0, 52, 74, 75, 70, 71, 66, 0,
	0, 67, 0, 72, 73, 0, 0, 0, 0, 0,
	0, 59, 68, 69, 54, 55, 56, 57, 58, 0,
	52, 74, 75, 70, 71, 66, 0, 0, 67, 0,
	72, 73, 0, 0, 0, 0, 0, 0, 0, 68,
	69, 54, 55, 56, 57, 58, 0, 52, 74, 75,
	72, 73, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 54, 55, 56, 57, 58, 0, 52, 74, 75,
}

var fcPact = [...]int16{
	90, -32768, -32768, 90, -32768, -32768, 225, 121, 120, 119,
	110, 79, 75, 623, 109, 492, 62, 159, 271, -25,
	-26, -32768, -32768, 623, 224, 623, 623, 623, 623, 623,
	623, 108, 224, -32768, -32768, -32768, 102, 90, -32768, 245,
	245, 259, 623, 44, 623, 254, -32768, -32768, 59, 549,
	623, -32768, 623, 623, 623, 623, 623, 623, 623, 623,
	623, 623, 623, 623, 623, 623, 623, 623, 623, 623,
	623, 623, 623, 623, 623, 623, -32768, 246, 178, 176,
	93, 97, -32768, -32768, -32768, 462, 152, -32768, 76, 76,
	76, 76, 76, -40, 549, 219, 28, 233, -18, 30,
	-32768, -23, 27, 94, 432, 90, 402, 31, -32768, 372,
	-32768, 549, 138, 138, 76, 76, 76, 753, 699, 726,
	672, 645, 549, 549, 131, 131, 773, 773, 773, 773,
	73, 73, 22, 252, 186, -32768, -32768, -32768, 214, -32768,
	623, -32768, 602, -32768, 232, -32768, 623, 39, -32768, -32768,
	-32768, 34, 19, -32768, -28, -32768, -32768, 245, 224, 623,
	-32768, 245, 90, -32768, 90, 623, -11, -15, -32768, 58,
	244, 33, 773, 223, -32768, -12, -32768, 141, -29, 549,
	-32768, -32768, 233, 623, -32768, 100, 522, -10, -8, 218,
	-32768, 281, 191, -32768, -32768, -32768, -32768, 206, -32768, -32768,
	232, 224, -32768, 549, 206, 623, -32768, -32768, -31, -32768,
	90, 89, 623, 204, -32768, 623, 46, -32768, 141, -32768,
	549, 224, -32768, 623, 342, -39, -32768, -41, -47, -32768,
	103, 312, -15, -32768, 90, 90, -19, 90, -32768, 90,
	90, -32768, 218, -32768,
}

var fcPgo = [...]int16{
	0, 369, 201, 11, 2, 7, 365, 353, 18, 348,
	340, 339, 338, 9, 4, 3, 334, 1, 322, 0,
	5, 21, 17, 310, 309, 12, 305, 36, 15, 293,
	8, 281, 280, 10,
}

var fcR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 4, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 6, 6, 7, 7,
	7, 8, 8, 9, 9, 10, 10, 11, 11, 12,
	12, 13, 14, 14, 15, 16, 16, 17, 17, 17,
	18, 18, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 20,
	20, 20, 21, 21, 22, 23, 24, 24, 25, 26,
	26, 27, 27, 28, 28, 29, 29, 30, 30, 31,
	31, 31, 31, 32, 32, 32, 33, 33,
}

var fcR2 = [...]int8{
	0, 1, 1, 0, 2, 1, 1, 4, 4, 6,
	4, 5, 9, 2, 2, 3, 8, 2, 10, 2,
	5, 7, 2, 2, 1, 1, 0, 1, 0, 2,
	2, 1, 2, 0, 2, 0, 1, 0, 3, 2,
	1, 4, 1, 1, 3, 0, 1, 0, 2, 6,
	0, 1, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 4, 2, 2, 2, 2,
	2, 5, 4, 3, 4, 3, 1, 1, 1, 3,
	1, 0, 0, 1, 4, 1, 3, 1, 3, 0,
	1, 3, 1, 5, 4, 0, 2, 2, 1, 3,
	2, 1, 3, 3, 1, 0, 1, 3,
}

var fcChk = [...]int16{
	-32768, -1, -2, -3, -4, -5, -6, 12, 15, 16,
	17, 19, 20, 18, 22, -19, -22, 25, 7, 28,
	29, -15, 58, 55, 46, 64, 49, 48, 50, 45,
	56, 21, 36, 4, 5, 6, 11, 61, -4, 10,
	9, 8, 55, 55, 55, 55, 58, 58, -18, -19,
	55, 58, 54, 42, 48, 49, 50, 51, 52, 45,
	43, 44, 39, 40, 33, 34, 32, 35, 46, 47,
	30, 31, 37, 38, 55, 56, 58, -7, -8, 50,
	41, -10, 5, 63, 63, -19, -30, 5, -19, -19,
	-19, -19, -19, -20, -19, 55, -30, 55, -2, -27,
	-28, 5, -27, 5, -19, 59, -19, 5, 58, -19,
	-19, -19, -19, -19, -19, -19, -19, -19, -19, -19,
	-19, -19, -19, -19, -19, -19, -19, -19, -19, -19,
	-19, -19, -20, -19, 5, 27, 27, -8, 55, 59,
	47, -31, 56, 50, 55, 65, 60, 6, -14, -15,
	58, -23, -24, -25, 5, 62, 58, 60, 63, 42,
	58, 55, 59, -5, 59, 60, 59, 59, 65, -9,
	26, 6, -19, -19, 65, -32, -33, -30, 5, -19,
	59, 59, 60, 63, -28, -30, -19, -26, -27, -5,
	-5, -19, 61, -16, -15, 58, 5, 59, 65, 59,
	60, 63, -25, -19, -29, 42, -21, -22, 59, -17,
	13, 14, 60, -12, -13, 23, -21, -33, -30, -21,
	-19, 63, -5, 55, -19, -11, -13, 24, -20, 58,
	-30, -19, 59, 62, 63, 63, -21, 59, -15, -3,
	-3, -14, -5, -17,
}

var fcDef = [...]int8{
	-2, -2, 1, -2, 5, 6, 0, 0, 0, 0,
	0, 0, 0, 50, 0, 0, 0, 28, 35, 27,
	0, 24, 25, 0, 0, 0, 0, 0, 0, 0,
	91, 0, 0, 86, 87, 88, 0, -2, 4, 0,
	0, 0, 0, 0, 0, 0, 13, 14, 0, 51,
	0, 17, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 91, 0, 19, 0, 0, 0,
	31, 0, 36, 22, 23, 0, 0, 108, 76, 77,
	78, 79, 80, 0, 90, 0, 0, 0, 0, 0,
	102, 0, 0, 0, 0, 26, 0, 0, 15, 0,
	53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
	63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
	73, 74, 0, 0, 33, 29, 30, 32, 0, 52,
	0, 107, 0, 111, 115, 83, 0, 0, 85, 42,
	43, 0, 95, 97, 0, 44, 7, 0, 0, 0,
	8, 99, 26, 10, 26, 0, 0, 45, 82, 0,
	0, 0, 75, 0, 110, 0, 114, 116, 108, 89,
	84, 94, 0, 0, 101, 105, 92, 0, 100, 47,
	11, 0, 0, 81, 46, 20, 34, 92, 109, 112,
	0, 0, 96, 98, 92, 0, 104, 93, 0, 9,
	26, 0, 0, 37, 40, 91, 0, 113, 117, 103,
	106, 0, 48, 0, 0, 0, 39, 0, 0, 21,
	92, 0, 0, 16, 26, 26, 0, 26, 12, -2,
	-2, 18, 47, 49,
}

var fcTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 64, 3, 3, 3, 52, 45, 3,
	55, 59, 50, 48, 60, 49, 54, 51, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 63, 58,
	46, 42, 47, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 56, 3, 65, 44, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 61, 43, 62,
}

var fcTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	53, 57,
}

var fcTok3 = [...]int8{
	0,
}

var fcErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	fcDebug        = 0
	fcErrorVerbose = false
)

type fcLexer interface {
	Lex(lval *fcSymType) int
	Error(s string)
}

type fcParser interface {
	Parse(fcLexer) int
	Lookahead() int
}

type fcParserImpl struct {
	lval  fcSymType
	stack [fcInitialStackSize]fcSymType
	char  int
}

func (p *fcParserImpl) Lookahead() int {
	return p.char
}

func fcNewParser() fcParser {
	return &fcParserImpl{}
}

const fcFlag = -32768

func fcTokname(c int) string {
	if c >= 1 && c-1 < len(fcToknames) {
		if fcToknames[c-1] != "" {
			return fcToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func fcStatname(s int) string {
	if s >= 0 && s < len(fcStatenames) {
		if fcStatenames[s] != "" {
			return fcStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func fcErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !fcErrorVerbose {
		return "syntax error"
	}

	for _, e := range fcErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + fcTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(fcPact[state])
	for tok := TOKSTART; tok-1 < len(fcToknames); tok++ {
		if n := base + tok; n >= 0 && n < fcLast && int(fcChk[int(fcAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if fcDef[state] == -2 {
		i := 0
		for fcExca[i] != -1 || int(fcExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; fcExca[i] >= 0; i += 2 {
			tok := int(fcExca[i])
			if tok < TOKSTART || fcExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if fcExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += fcTokname(tok)
	}
	return res
}

func fclex1(lex fcLexer, lval *fcSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(fcTok1[0])
		goto out
	}
	if char < len(fcTok1) {
		token = int(fcTok1[char])
		goto out
	}
	if char >= fcPrivate {
		if char < fcPrivate+len(fcTok2) {
			token = int(fcTok2[char-fcPrivate])
			goto out
		}
	}
	for i := 0; i < len(fcTok3); i += 2 {
		token = int(fcTok3[i+0])
		if token == char {
			token = int(fcTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(fcTok2[1]) /* unknown char */
	}
	if fcDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", fcTokname(token), uint(char))
	}
	return char, token
}

func fcParse(fclex fcLexer) int {
	return fcNewParser().Parse(fclex)
}

func (fcrcvr *fcParserImpl) Parse(fclex fcLexer) int {
	var fcn int
	var fcVAL fcSymType
	var fcDollar []fcSymType
	_ = fcDollar // silence set and not used
	fcS := fcrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	fcstate := 0
	fcrcvr.char = -1
	fctoken := -1 // fcrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		fcstate = -1
		fcrcvr.char = -1
		fctoken = -1
	}()
	fcp := -1
	goto fcstack

ret0:
	return 0

ret1:
	return 1

fcstack:
	/* put a state and value onto the stack */
	if fcDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", fcTokname(fctoken), fcStatname(fcstate))
	}

	fcp++
	if fcp >= len(fcS) {
		nyys := make([]fcSymType, len(fcS)*2)
		copy(nyys, fcS)
		fcS = nyys
	}
	fcS[fcp] = fcVAL
	fcS[fcp].yys = fcstate

fcnewstate:
	fcn = int(fcPact[fcstate])
	if fcn <= fcFlag {
		goto fcdefault /* simple state */
	}
	if fcrcvr.char < 0 {
		fcrcvr.char, fctoken = fclex1(fclex, &fcrcvr.lval)
	}
	fcn += fctoken
	if fcn < 0 || fcn >= fcLast {
		goto fcdefault
	}
	fcn = int(fcAct[fcn])
	if int(fcChk[fcn]) == fctoken { /* valid shift */
		fcrcvr.char = -1
		fctoken = -1
		fcVAL = fcrcvr.lval
		fcstate = fcn
		if Errflag > 0 {
			Errflag--
		}
		goto fcstack
	}

fcdefault:
	/* default state action */
	fcn = int(fcDef[fcstate])
	if fcn == -2 {
		if fcrcvr.char < 0 {
			fcrcvr.char, fctoken = fclex1(fclex, &fcrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if fcExca[xi+0] == -1 && int(fcExca[xi+1]) == fcstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			fcn = int(fcExca[xi+0])
			if fcn < 0 || fcn == fctoken {
				break
			}
		}
		fcn = int(fcExca[xi+1])
		if fcn < 0 {
			goto ret0
		}
	}
	if fcn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			fclex.Error(fcErrorMessage(fcstate, fctoken))
			Nerrs++
			if fcDebug >= 1 {
				__yyfmt__.Printf("%s", fcStatname(fcstate))
				__yyfmt__.Printf(" saw %s\n", fcTokname(fctoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for fcp >= 0 {
				fcn = int(fcPact[fcS[fcp].yys]) + fcErrCode
				if fcn >= 0 && fcn < fcLast {
					fcstate = int(fcAct[fcn]) /* simulate a shift of "error" */
					if int(fcChk[fcstate]) == fcErrCode {
						goto fcstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if fcDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", fcS[fcp].yys)
				}
				fcp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if fcDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", fcTokname(fctoken))
			}
			if fctoken == fcEofCode {
				goto ret1
			}
			fcrcvr.char = -1
			fctoken = -1
			goto fcnewstate /* try again in the same state */
		}
	}

	/* reduction by production fcn */
	if fcDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", fcn, fcStatname(fcstate))
	}

	fcnt := fcn
	fcpt := fcp
	_ = fcpt // guard against "declared and not used"

	fcp -= int(fcR2[fcn])
	// fcp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if fcp+1 >= len(fcS) {
		nyys := make([]fcSymType, len(fcS)*2)
		copy(nyys, fcS)
		fcS = nyys
	}
	fcVAL = fcS[fcp+1]

	/* consult goto table to find next state */
	fcn = int(fcR1[fcn])
	fcg := int(fcPgo[fcn])
	fcj := fcg + fcS[fcp].yys + 1

	if fcj >= fcLast {
		fcstate = int(fcAct[fcg])
	} else {
		fcstate = int(fcAct[fcj])
		if int(fcChk[fcstate]) != -fcn {
			fcstate = int(fcAct[fcg])
		}
	}
	// dummy call; replaced with literal code
	switch fcnt {

	case 1:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:44
		{
			fclex.(*parserLexer).result = fcDollar[1].n.([]any)
		}
	case 3:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:50
		{
			fcVAL.n = []any{}
		}
	case 4:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:52
		{
			fcVAL.n = cons(fcDollar[1].n.([]any), fcDollar[2].n)
		}
	case 5:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:53
		{
			fcVAL.n = []any{fcDollar[1].n}
		}
	case 6:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:55
		{
			fclex.(*parserLexer).info(fcDollar[1].n)
			fcVAL.n = fcDollar[1].n
		}
	case 7:
		fcDollar = fcS[fcpt-4 : fcpt+1]
//line parser.y:57
		{
			fcVAL.n = []any{Sym("var"), fcDollar[3].n, fcDollar[1].n}
		}
	case 8:
		fcDollar = fcS[fcpt-4 : fcpt+1]
//line parser.y:58
		{
			fcVAL.n = []any{Sym("const"), fcDollar[3].n, fcDollar[1].n}
		}
	case 9:
		fcDollar = fcS[fcpt-6 : fcpt+1]
//line parser.y:59
		{
			fcVAL.n = []any{Sym("if"), fcDollar[3].n, fcDollar[5].n, fcDollar[6].n}
		}
	case 10:
		fcDollar = fcS[fcpt-4 : fcpt+1]
//line parser.y:60
		{
			fcVAL.n = []any{Sym("loop"), fcDollar[4].n}
		}
	case 11:
		fcDollar = fcS[fcpt-5 : fcpt+1]
//line parser.y:61
		{
			fcVAL.n = []any{Sym("while"), fcDollar[3].n, fcDollar[5].n}
		}
	case 12:
		fcDollar = fcS[fcpt-9 : fcpt+1]
//line parser.y:62
		{
			fcVAL.n = []any{Sym("for"), fcDollar[3].n, fcDollar[5].n, fcDollar[7].n, fcDollar[9].n}
		}
	case 13:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:63
		{
			fcVAL.n = []any{Sym("break")}
		}
	case 14:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:64
		{
			fcVAL.n = []any{Sym("continue")}
		}
	case 15:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:65
		{
			fcVAL.n = []any{Sym("return"), fcDollar[2].n}
		}
	case 16:
		fcDollar = fcS[fcpt-8 : fcpt+1]
//line parser.y:66
		{
			fcVAL.n = []any{Sym("switch"), fcDollar[3].n, fcDollar[6].n, fcDollar[7].n}
		}
	case 17:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:67
		{
			fcVAL.n = []any{Sym("exp"), fcDollar[1].n}
		}
	case 18:
		fcDollar = fcS[fcpt-10 : fcpt+1]
//line parser.y:69
		{
			fcVAL.n = []any{Sym("function"), fcDollar[1].n, fcDollar[3].n, fcDollar[5].n, fcDollar[8].n, fcDollar[9].n, fcDollar[10].n}
		}
	case 19:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:70
		{
			fcVAL.n = []any{Sym("options"), fcDollar[1].n}
		}
	case 20:
		fcDollar = fcS[fcpt-5 : fcpt+1]
//line parser.y:71
		{
			fcVAL.n = []any{Sym("use"), fcDollar[3].n, fcDollar[4].n, fcDollar[2].n}
		}
	case 21:
		fcDollar = fcS[fcpt-7 : fcpt+1]
//line parser.y:72
		{
			fcVAL.n = []any{Sym("include"), fcDollar[4].n, fcDollar[2].n, fcDollar[6].n}
		}
	case 22:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:73
		{
			fcVAL.n = []any{Sym("public")}
		}
	case 23:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:74
		{
			fcVAL.n = []any{Sym("private")}
		}
	case 24:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:75
		{
			fcVAL.n = []any{Sym("block"), fcDollar[1].n}
		}
	case 25:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:76
		{
			fcVAL.n = []any{Sym("blank")}
		}
	case 26:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:78
		{
			fcVAL.n = nil
		}
	case 27:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:79
		{
			fcVAL.n = Sym("public")
		}
	case 28:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:81
		{
			fcVAL.n = nil
		}
	case 29:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:82
		{
			fcVAL.n = fcDollar[1].n
		}
	case 30:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:83
		{
			fcVAL.n = fcDollar[1].n
		}
	case 31:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:85
		{
			fcVAL.n = []any{fcDollar[1].n}
		}
	case 32:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:86
		{
			fcVAL.n = cons([]any{fcDollar[1].n}, fcDollar[2].n.([]any)...)
		}
	case 33:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:88
		{
			fcVAL.n = nil
		}
	case 34:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:89
		{
			fcVAL.n = fcDollar[2].n
		}
	case 35:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:91
		{
			fcVAL.n = nil
		}
	case 37:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:94
		{
			fcVAL.n = nil
		}
	case 38:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:95
		{
			fcVAL.n = fcDollar[3].n
		}
	case 39:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:97
		{
			fcVAL.n = cons(fcDollar[1].n.([]any), fcDollar[2].n)
		}
	case 40:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:98
		{
			fcVAL.n = []any{fcDollar[1].n}
		}
	case 41:
		fcDollar = fcS[fcpt-4 : fcpt+1]
//line parser.y:100
		{
			fcVAL.n = []any{fcDollar[2].n, fcDollar[4].n}
		}
	case 43:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:103
		{
			fcVAL.n = nil
		}
	case 44:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:105
		{
			fcVAL.n = fcDollar[2].n
		}
	case 45:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:107
		{
			fcVAL.n = nil
		}
	case 47:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:110
		{
			fcVAL.n = nil
		}
	case 48:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:111
		{
			fcVAL.n = fcDollar[2].n
		}
	case 49:
		fcDollar = fcS[fcpt-6 : fcpt+1]
//line parser.y:112
		{
			fcVAL.n = []any{Sym("if"), fcDollar[3].n, fcDollar[5].n, fcDollar[6].n}
		}
	case 50:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:116
		{
			fcVAL.n = nil
		}
	case 52:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:119
		{
			fcVAL.n = fcDollar[2].n
		}
	case 53:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:120
		{
			fcVAL.n = []any{Sym("dot"), fcDollar[1].n, fcDollar[3].n}
		}
	case 54:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:121
		{
			fcVAL.n = []any{Sym("load"), fcDollar[1].n, fcDollar[3].n}
		}
	case 55:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:122
		{
			fcVAL.n = []any{Sym("add"), fcDollar[1].n, fcDollar[3].n}
		}
	case 56:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:123
		{
			fcVAL.n = []any{Sym("sub"), fcDollar[1].n, fcDollar[3].n}
		}
	case 57:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:124
		{
			fcVAL.n = []any{Sym("mul"), fcDollar[1].n, fcDollar[3].n}
		}
	case 58:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:125
		{
			fcVAL.n = []any{Sym("div"), fcDollar[1].n, fcDollar[3].n}
		}
	case 59:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:126
		{
			fcVAL.n = []any{Sym("mod"), fcDollar[1].n, fcDollar[3].n}
		}
	case 60:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:127
		{
			fcVAL.n = []any{Sym("and"), fcDollar[1].n, fcDollar[3].n}
		}
	case 61:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:128
		{
			fcVAL.n = []any{Sym("or"), fcDollar[1].n, fcDollar[3].n}
		}
	case 62:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:129
		{
			fcVAL.n = []any{Sym("xor"), fcDollar[1].n, fcDollar[3].n}
		}
	case 63:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:130
		{
			fcVAL.n = []any{Sym("land"), fcDollar[1].n, fcDollar[3].n}
		}
	case 64:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:131
		{
			fcVAL.n = []any{Sym("lor"), fcDollar[1].n, fcDollar[3].n}
		}
	case 65:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:132
		{
			fcVAL.n = []any{Sym("load"), fcDollar[1].n, []any{Sym("add"), fcDollar[1].n, fcDollar[3].n}}
		}
	case 66:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:133
		{
			fcVAL.n = []any{Sym("load"), fcDollar[1].n, []any{Sym("sub"), fcDollar[1].n, fcDollar[3].n}}
		}
	case 67:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:134
		{
			fcVAL.n = []any{Sym("eq"), fcDollar[1].n, fcDollar[3].n}
		}
	case 68:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:135
		{
			fcVAL.n = []any{Sym("ne"), fcDollar[1].n, fcDollar[3].n}
		}
	case 69:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:136
		{
			fcVAL.n = []any{Sym("lt"), fcDollar[1].n, fcDollar[3].n}
		}
	case 70:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:137
		{
			fcVAL.n = []any{Sym("gt"), fcDollar[1].n, fcDollar[3].n}
		}
	case 71:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:138
		{
			fcVAL.n = []any{Sym("le"), fcDollar[1].n, fcDollar[3].n}
		}
	case 72:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:139
		{
			fcVAL.n = []any{Sym("ge"), fcDollar[1].n, fcDollar[3].n}
		}
	case 73:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:140
		{
			fcVAL.n = []any{Sym("shift_left"), fcDollar[1].n, fcDollar[3].n}
		}
	case 74:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:141
		{
			fcVAL.n = []any{Sym("shift_right"), fcDollar[1].n, fcDollar[3].n}
		}
	case 75:
		fcDollar = fcS[fcpt-4 : fcpt+1]
//line parser.y:142
		{
			fcVAL.n = []any{Sym("cast"), fcDollar[4].n, fcDollar[2].n}
		}
	case 76:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:143
		{
			fcVAL.n = []any{Sym("not"), fcDollar[2].n}
		}
	case 77:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:144
		{
			fcVAL.n = []any{Sym("uminus"), fcDollar[2].n}
		}
	case 78:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:145
		{
			fcVAL.n = fcDollar[2].n
		}
	case 79:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:146
		{
			fcVAL.n = []any{Sym("deref"), fcDollar[2].n}
		}
	case 80:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:147
		{
			fcVAL.n = []any{Sym("ref"), fcDollar[2].n}
		}
	case 81:
		fcDollar = fcS[fcpt-5 : fcpt+1]
//line parser.y:148
		{
			fcVAL.n = []any{Sym("call"), fcDollar[1].n, fcDollar[3].n, fcDollar[5].n}
		}
	case 82:
		fcDollar = fcS[fcpt-4 : fcpt+1]
//line parser.y:149
		{
			fcVAL.n = []any{Sym("index"), fcDollar[1].n, fcDollar[3].n}
		}
	case 83:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:150
		{
			fcVAL.n = []any{Sym("array"), fcDollar[2].n}
		}
	case 84:
		fcDollar = fcS[fcpt-4 : fcpt+1]
//line parser.y:151
		{
			fcVAL.n = []any{Sym("incbin"), fcDollar[3].n}
		}
	case 85:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:152
		{
			fcVAL.n = []any{Sym("lambda"), fcDollar[2].n, fcDollar[3].n}
		}
	case 89:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:157
		{
			fcVAL.n = cons(fcDollar[1].n.([]any), fcDollar[3].n)
		}
	case 90:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:158
		{
			fcVAL.n = []any{fcDollar[1].n}
		}
	case 91:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:159
		{
			fcVAL.n = []any{}
		}
	case 92:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:163
		{
			fcVAL.n = nil
		}
	case 94:
		fcDollar = fcS[fcpt-4 : fcpt+1]
//line parser.y:165
		{
			fcVAL.n = fcDollar[3].n
		}
	case 95:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:167
		{
			fcVAL.n = OMapFromPairs(fcDollar[1].n.([]any))
		}
	case 96:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:168
		{
			fcVAL.n = cons(fcDollar[1].n.([]any), fcDollar[3].n.([]any)...)
		}
	case 98:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:170
		{
			fcVAL.n = []any{fcDollar[1].n, fcDollar[3].n}
		}
	case 99:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:174
		{
			fcVAL.n = []any{}
		}
	case 101:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:176
		{
			fcVAL.n = cons(fcDollar[1].n.([]any), fcDollar[3].n)
		}
	case 102:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:177
		{
			fcVAL.n = []any{fcDollar[1].n}
		}
	case 103:
		fcDollar = fcS[fcpt-5 : fcpt+1]
//line parser.y:179
		{
			fcVAL.n = []any{fcDollar[1].n, fcDollar[3].n, fcDollar[4].n, fcDollar[5].n}
		}
	case 104:
		fcDollar = fcS[fcpt-4 : fcpt+1]
//line parser.y:180
		{
			fcVAL.n = []any{fcDollar[1].n, nil, fcDollar[3].n, fcDollar[4].n}
		}
	case 105:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:182
		{
			fcVAL.n = nil
		}
	case 106:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:183
		{
			fcVAL.n = fcDollar[2].n
		}
	case 107:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:187
		{
			fcVAL.n = cons(fcDollar[2].n.([]any), fcDollar[1].n)
		}
	case 109:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:190
		{
			fcVAL.n = []any{Sym("array"), fcDollar[2].n}
		}
	case 110:
		fcDollar = fcS[fcpt-2 : fcpt+1]
//line parser.y:191
		{
			fcVAL.n = []any{Sym("array"), nil}
		}
	case 111:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:192
		{
			fcVAL.n = []any{Sym("pointer")}
		}
	case 112:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:193
		{
			fcVAL.n = []any{Sym("lambda"), fcDollar[2].n}
		}
	case 113:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:195
		{
			fcVAL.n = cons(fcDollar[1].n.([]any), fcDollar[3].n)
		}
	case 114:
		fcDollar = fcS[fcpt-1 : fcpt+1]
//line parser.y:196
		{
			fcVAL.n = []any{fcDollar[1].n}
		}
	case 115:
		fcDollar = fcS[fcpt-0 : fcpt+1]
//line parser.y:197
		{
			fcVAL.n = []any{}
		}
	case 117:
		fcDollar = fcS[fcpt-3 : fcpt+1]
//line parser.y:200
		{
			fcVAL.n = []any{fcDollar[1].n, fcDollar[3].n}
		}
	}
	goto fcstack /* stack new state and value */
}
